In [ ]:
"""
### 실습준비 @ 129.254.23.132

2024-11-11 ~ 2024-11-15
by 김일한 ihank@naver.com

http://129.254.23.13/0.core/index.php
https://www.python.org/         최신버전  3.13.0 (No!) --> (패키지 업데이트 고려) --> 3.10.9 
https://code.visualstudio.com/  CTRL + "," 로 세팅설정에서 마우스줌 활성 // ipynb (json) 사용
https://git-scm.com/downloads/win
file:///C:/Users/std/AppData/Local/Programs/Git/ReleaseNotes.html  

""";
import os
import sys
print(os.getcwd())
print(sys.version)
def ia(o): [print("%04d:%20s:%s"%(i,a,getattr(o,a)) for (i,a) in enumerate(dir(o),1))]


c:\X
3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]


In [2]:
!pip install tensorflow
!pip install pandas
!pip install matplotlib

## 텐서플로 특징
1) 기본적으로 "텐서"를 활용한 "그래프" 수치연산도구
2) "그래프" 란? : "노드"와 "엣지"로 구성된 기하적 (계산) 모형
3) "노드" 란? : 연산 및 데이터 정의
4) "엣지"란? : "노드"를 연결 (데이터의 흐름 (=플로)
5) "텐서"란? : 다차원 데이터 (함수) 배열
6) "텐서플로" - 텐서가 노드에서 연산되고 엣지를 통해 돌아다닌다. 

In [3]:
import tensorflow as tf
import matplotlib.pyplot as plt
import pandas as pd


In [13]:
for (i,a) in enumerate(dir(tf),1):
    print(i,a)

1 AggregationMethod
2 Assert
3 CriticalSection
4 DType
5 DeviceSpec
6 GradientTape
7 Graph
8 IndexedSlices
9 IndexedSlicesSpec
10 Module
11 Operation
12 OptionalSpec
13 RaggedTensor
14 RaggedTensorSpec
15 RegisterGradient
16 SparseTensor
17 SparseTensorSpec
18 Tensor
19 TensorArray
20 TensorArraySpec
21 TensorShape
22 TensorSpec
23 TypeSpec
24 UnconnectedGradients
25 Variable
26 VariableAggregation
27 VariableSynchronization
28 _API_MODULE
29 _KerasLazyLoader
30 __all__
31 __builtins__
32 __cached__
33 __compiler_version__
34 __cxx11_abi_flag__
35 __cxx_version__
36 __doc__
37 __file__
38 __git_version__
39 __internal__
40 __loader__
41 __monolithic_build__
42 __name__
43 __operators__
44 __package__
45 __path__
46 __spec__
47 __version__
48 _api
49 _compat
50 _current_file_location
51 _current_module
52 _distutils
53 _fi
54 _initializers
55 _inspect
56 _kernel_dir
57 _ll
58 _losses
59 _major_api_version
60 _metrics
61 _module_dir
62 _module_util
63 _names_with_underscore
64 _optimizer

## scalar data

In [5]:
s1 = 10
s2 = 'abc'
s3 = 3.14

## Vector Data

In [6]:
= [[1,2,3,], [4,5]]

SyntaxError: invalid syntax (2507155528.py, line 1)

In [ ]:
V

[[1, 2, 3], [4, 5]]

In [ ]:
T = [[[1,2,3],[4,5,6]],2*[[1,2,3],[4,5,6]]]

In [ ]:
T


[[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]]]

In [ ]:
print(T)

[[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]]]


In [ ]:
tf.Variable(T)

ValueError: Can't convert non-rectangular Python sequence to Tensor.

In [ ]:
t1=tf.constant(s1)

In [ ]:
t1

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [ ]:
tf

<module 'tensorflow' from 'c:\\Python310\\lib\\site-packages\\tensorflow\\__init__.py'>

In [ ]:
v3=tf.Variable(s3)

In [ ]:
tf.Variable([1,2,3])*tf.Variable([4,5,6])*tf.constant(-1)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ -4, -10, -18], dtype=int32)>

In [ ]:
f = tf.constant([[1],[2],[3]])
g = tf.constant([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
f

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3]], dtype=int32)>

In [ ]:
g

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [ ]:
f*g

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 8, 10, 12],
       [21, 24, 27]], dtype=int32)>

In [ ]:
f+g

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]], dtype=int32)>

In [ ]:
## 행렬곱
A = [[1,3],[5,7]]
B = [[1,2],[2,5]]

In [ ]:
tf.Variable(A)*tf.Variable(B)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  6],
       [10, 35]], dtype=int32)>

In [ ]:
tf.Variable(A)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 3],
       [5, 7]], dtype=int32)>

In [ ]:
tf.Variable(B)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [2, 5]], dtype=int32)>

In [ ]:
tf.Variable(A)*tf.Variable(B)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  6],
       [10, 35]], dtype=int32)>

In [ ]:
tf.matmul(tf.Variable(A),tf.Variable(B)) == tf.matmul(A,B)

<tf.Tensor: shape=(2, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True]])>

In [ ]:
tf.Variable(A)*tf.Variable(B) == tf.multiply(A,B)

<tf.Tensor: shape=(2, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True]])>

In [ ]:
tf.square([1,2,3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 4, 9], dtype=int32)>

In [ ]:
tf.Variable([1,2,3])**2

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 4, 9], dtype=int32)>

In [ ]:
tf.reduce_mean(tf.Variable([1.0,2,3]))

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [ ]:
tf.reduce_sum(tf.Variable([1.0,2,3]))

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>