In [1]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, SimpleRNN

In [2]:
x = np.array( [[[1,2],[3,4],[5,6],[7,8]]], dtype=np.float32)
x

array([[[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]]], dtype=float32)

In [3]:
x.shape

(1, 4, 2)

In [4]:
rnn = SimpleRNN( 3, return_sequences= True)
rnn( x )

<tf.Tensor: shape=(1, 4, 3), dtype=float32, numpy=
array([[[-0.18991694,  0.04271767, -0.9889424 ],
        [-0.7577331 ,  0.6399288 , -0.999958  ],
        [-0.9858515 ,  0.46916384, -1.        ],
        [-0.9968794 ,  0.2600664 , -1.        ]]], dtype=float32)>

In [5]:
w = rnn.get_weights()

In [6]:
print( w[0].shape)
print( w[1].shape)
print( w[2].shape) # bias

(2, 3)
(3, 3)
(3,)


In [14]:
from __ import *

In [13]:
import os
print(os.getcwd())

c:\X\test


In [12]:
cd ..\

c:\X\test


C:\Users\std\AppData\Roaming\Python\Python310\site-packages\IPython\core\magics\osm.py:417: UserWarning: This is now an optional IPython functionality, setting dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]


In [15]:
QQ

<function __.QQ(o)>

In [16]:
AA

<function __.AA(e)>

In [17]:
ZZ

<function __.ZZ()>

In [18]:
QQ(QQ)

0001:     __annotations__:                                                                                                  {}
0002:        __builtins__:{'__name__': 'builtins', '__doc__': "Built-in functions, exceptions, and other objects.\n\nNoteworth >>>>> excess <<<<<
0003:            __call__:                                <method-wrapper '__call__' of function object at 0x000002E540A5F250>
0004:           __class__:                                                                                  <class 'function'>
0005:         __closure__:                                                                                                None
0006:            __code__:                              <code object QQ at 0x000002E540673940, file "c:\X\test\__.py", line 6>
0007:        __defaults__:                                                                                                None
0008:         __delattr__:                             <method-wrapper '__delattr__' of func

In [19]:
QQ(AA)

0001:     __annotations__:                                                                                                  {}
0002:        __builtins__:{'__name__': 'builtins', '__doc__': "Built-in functions, exceptions, and other objects.\n\nNoteworth >>>>> excess <<<<<
0003:            __call__:                                <method-wrapper '__call__' of function object at 0x000002E540A5F2E0>
0004:           __class__:                                                                                  <class 'function'>
0005:         __closure__:                                                                                                None
0006:            __code__:                              <code object AA at 0x000002E5406728C0, file "c:\X\test\__.py", line 7>
0007:        __defaults__:                                                                                                None
0008:         __delattr__:                             <method-wrapper '__delattr__' of func