In [1]:
print('hello')

hello


In [2]:
import tensorflow as tf

## scalar data

In [4]:
s1 = 10
s2 = 'abc'
s3 = 3.14

### vector data

In [ ]:
v = [10,20,30] # (3,)

## matrix data

In [ ]:
m =[ [10,20,30],[10,20,30] ] #( 2, 3)

## 3d tensor

In [ ]:
# (2,2,3)
d3 = [ [ [10,20,30],[10,20,30] ],[ [100,200,300],[10,20,30] ] ]

### 텐서노드
- constant:읽기전용
- Variable:읽기 쓰기

In [7]:
s1 = 10
c1 = tf.constant( s1 )
c1

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [8]:
c1.numpy()

np.int32(10)

In [10]:
c1.numpy().item()

10

In [11]:
v1 = tf.constant( [10,20,30])
v1

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 20, 30], dtype=int32)>

In [12]:
v1.numpy()

array([10, 20, 30], dtype=int32)

In [13]:
m1 = tf.constant( [[10,20],[30,40]] )
m1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

### 연산노드(산술연산)
- broad casting: 큰차원으로 자동확장
- element wise: 요소별(동일인덱스끼리) 연산

In [ ]:
a = tf.constant( 3 )
b = tf.constant( [1,2,3])
c = tf.add( a,b) # a+b  [3,3,3] + [1,2,3] = [4,5,6]
c

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 5, 6], dtype=int32)>

In [15]:
c.numpy()

array([4, 5, 6], dtype=int32)

In [ ]:
d = tf.multiply( a,b ) # a*b
d

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 6, 9], dtype=int32)>

In [17]:
e= c- d #tf.subtract(c,d)
e

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 1, -1, -3], dtype=int32)>

In [ ]:
## broadcasting 

In [18]:
f = tf.constant( [1,2,3])
g = tf.constant( [ [1,2,3],[4,5,6],[7,8,9]])
h = f+g # tf.add(f,g)
h

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]], dtype=int32)>

In [22]:
i = tf.constant( [[1],[2],[3]])
j = tf.constant( [ [1,2,3],[4,5,6],[7,8,9]])
k = i+j # tf.add(f,g)
k

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]], dtype=int32)>

### 행렬곱

In [25]:
o = tf.constant( [[1,2],[3,4]] )
p = tf.constant( [[5,6],[7,8]])
q = tf.multiply(o,p)
r = tf.matmul( o,p)

In [26]:
q

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 12],
       [21, 32]], dtype=int32)>

In [27]:
r

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 22],
       [43, 50]], dtype=int32)>

## 많이 사용 operation

In [ ]:
s = [1,2,3]
t = tf.square( s ) # s**2
t

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 4, 9], dtype=int32)>

In [29]:
u = tf.reduce_mean( s )
u

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [30]:
v = tf.reduce_sum( s )
v

<tf.Tensor: shape=(), dtype=int32, numpy=6>

## Varibale

In [31]:
v = tf.Variable( 10 )
v

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=10>

In [32]:
#v.assign( 3 )
#v.assign_add( 3 )
v.assign_sub(3)
v

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=7>