In [ ]:
!pip install scikit-learn

In [6]:
import tensorflow as tf
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [3]:
data = [[828, 920, 1234567, 1020, 1111],
            [824, 910, 2345612, 1090, 1234],
            [880, 900, 3456123, 1010, 1000],
            [870, 990, 2312123, 1001, 1122],
            [860, 980, 3223123, 1008, 1133],
            [850, 970, 2432123, 1100, 1221]]
data = np.float32(data)

In [4]:
df = pd.DataFrame( data )
df

0      1          2       3       4
0  828.0  920.0  1234567.0  1020.0  1111.0
1  824.0  910.0  2345612.0  1090.0  1234.0
2  880.0  900.0  3456123.0  1010.0  1000.0
3  870.0  990.0  2312123.0  1001.0  1122.0
4  860.0  980.0  3223123.0  1008.0  1133.0
5  850.0  970.0  2432123.0  1100.0  1221.0

In [7]:
x_data = df.iloc[:, :-1].values
y_data = df.iloc[:, [-1]].values

In [10]:
# 3.14e+02
3.14e-2

0.0314

In [11]:
scaleF = MinMaxScaler()
x_dataN = scaleF.fit_transform( x_data )

In [13]:
scaleL = MinMaxScaler()
y_dataN = scaleL.fit_transform( y_data )

In [15]:
dense = Dense( units=1, input_dim=4)# w:3x1, b:1
model = Sequential( [dense] )
model.compile( loss='mse', optimizer= Adam(0.1) )
h = model.fit( x_dataN, y_dataN, epochs= 500)

c:\Python310\lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 399ms/step - loss: 1.2022
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 0.7025
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.3928
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.2545
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 0.2377
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.2772
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.3177
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.3278
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.3009
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.2466
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 0.1813
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.1211
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0779
Epoch 14/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0573
Epoch 15/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 0.0577
Epoch 16/500
1/1 ━

In [17]:
#828, 920, 1234567, 1020 예측
xd =scaleF.transform( [[828, 920, 1234567, 1020]] )
xd

array([[7.14281425e-02, 2.22222470e-01, 1.00739044e-08, 1.91919606e-01]])

In [18]:
pred = model.predict( xd )
pred

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step


array([[0.5250529]], dtype=float32)

In [19]:
scaleL.inverse_transform( pred )

array([[1122.8623]], dtype=float32)