In [1]:
import tensorflow as tf
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [4]:
x_data = np.array( [[1,3],[2,2],[3,1],[4,6],[5,5],[6,2]] )
y_data = np.array( [[0],[0],[0],[1],[1],[1]] )

In [ ]:
# z = tf.matmul( x, w ) + b
# hx = sigmoid( z )

In [ ]:
# dense = Dense( units=1, input_dim=2, activation='sigmoid')# w:2x1, b=1
# dense( tf.constant( x_data, tf.float32) )

c:\Python310\lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


<tf.Tensor: shape=(6, 1), dtype=float32, numpy=
array([[0.921977  ],
       [0.85900867],
       [0.75853145],
       [0.99440426],
       [0.98920375],
       [0.90798616]], dtype=float32)>

In [7]:
dense = Dense( units=1, input_dim=2, activation='sigmoid')
model = Sequential( [dense])
model.compile( loss='binary_crossentropy', optimizer=Adam(0.1),
              metrics=['acc'] )
h = model.fit( x_data, y_data, epochs=500)

Epoch 1/500


c:\Python310\lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 688ms/step - acc: 0.5000 - loss: 0.6602
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - acc: 0.5000 - loss: 0.6201
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - acc: 0.5000 - loss: 0.5892
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - acc: 0.5000 - loss: 0.5661
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.6667 - loss: 0.5486
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - acc: 0.6667 - loss: 0.5345
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.6667 - loss: 0.5213
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - acc: 0.6667 - loss: 0.5077
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - acc: 0.6667 - loss: 0.4932
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - acc: 0.6667 - loss: 0.4777
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.8333 - loss: 0.4617
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - acc: 0.8333 - loss: 0.4460
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - acc: 0.

In [12]:
# dense( tf.constant( x_data, tf.float32) ).numpy() >0.5
dense( tf.constant( x_data, tf.float32) )

<tf.Tensor: shape=(6, 1), dtype=float32, numpy=
array([[0.00312197],
       [0.00764463],
       [0.01859683],
       [0.9969669 ],
       [0.9987647 ],
       [0.9904501 ]], dtype=float32)>

In [15]:
pred = ( model.predict( x_data) > 0.5) + 0
pred

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step


array([[0],
       [0],
       [0],
       [1],
       [1],
       [1]])

In [17]:
(pred == y_data).mean()

np.float64(1.0)

In [18]:
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix

In [19]:
accuracy_score( y_data, pred)

1.0

In [20]:
f1_score( y_data, pred )

np.float64(1.0)

In [21]:
confusion_matrix( y_data, pred)

array([[3, 0],
       [0, 3]])

Pregnancies : 임신횟수
Glucose : 포도당 부하 검사 수치
BloodPressure : 혈압
SkinThickness : 팔 삼두근 뒤쪽의 피하지방 측정값
Insulin : 혈청 인슐린
BMI : 체질량 지수
DiabetesPedigreeFunction : 당뇨 내력 가중치 값
Age : 나이
Outcome : 당뇨여부(0 또는 1)

In [ ]:
### 15분 퀴즈 
# 케라스로 학습
# 정확도, f1_score, confusion matrix
# 6	148	72	35	0	33.6	0.627	50 당뇨유무예측
df = pd.read_csv('data/pima-indians-diabetes.data.csv')
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [23]:
x_data = df.iloc[:, :-1].values
y_data = df.iloc[:, [-1] ].values

In [24]:
x_data.shape

(768, 8)

In [26]:
df.corr()

Pregnancies   Glucose  BloodPressure  SkinThickness  \
Pregnancies                  1.000000  0.129459       0.141282      -0.081672   
Glucose                      0.129459  1.000000       0.152590       0.057328   
BloodPressure                0.141282  0.152590       1.000000       0.207371   
SkinThickness               -0.081672  0.057328       0.207371       1.000000   
Insulin                     -0.073535  0.331357       0.088933       0.436783   
BMI                          0.017683  0.221071       0.281805       0.392573   
DiabetesPedigreeFunction    -0.033523  0.137337       0.041265       0.183928   
Age                          0.544341  0.263514       0.239528      -0.113970   
Outcome                      0.221898  0.466581       0.065068       0.074752   

                           Insulin       BMI  DiabetesPedigreeFunction  \
Pregnancies              -0.073535  0.017683                 -0.033523   
Glucose                   0.331357  0.221071                  0.137337   
BloodPressure             0.088933  0.281805                  0.041265   
SkinThickness             0.436783  0.392573                  0.183928   
Insulin                   1.000000  0.197859                  0.185071   
BMI                       0.197859  1.000000                  0.140647   
DiabetesPedigreeFunction  0.185071  0.140647                  1.000000   
Age                      -0.042163  0.036242                  0.033561   
Outcome                   0.130548  0.292695                  0.173844   

                               Age   Outcome  
Pregnancies               0.544341  0.221898  
Glucose                   0.263514  0.466581  
BloodPressure             0.239528  0.065068  
SkinThickness            -0.113970  0.074752  
Insulin                  -0.042163  0.130548  
BMI                       0.036242  0.292695  
DiabetesPedigreeFunction  0.033561  0.173844  
Age                       1.000000  0.238356  
Outcome                   0.238356  1.000000

In [25]:
dense = Dense( units=1, input_dim=8, activation='sigmoid')
model = Sequential( [dense])
model.compile( loss='binary_crossentropy', optimizer=Adam(0.1),
              metrics=['acc'] )
h = model.fit( x_data, y_data, epochs=500)

Epoch 1/500


c:\Python310\lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


24/24 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - acc: 0.5190 - loss: 9.2458  
Epoch 2/500
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.6010 - loss: 2.1444  
Epoch 3/500
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - acc: 0.5569 - loss: 1.6369 
Epoch 4/500
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - acc: 0.5492 - loss: 1.7672
Epoch 5/500
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - acc: 0.5454 - loss: 2.0185
Epoch 6/500
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.5919 - loss: 1.54350
Epoch 7/500
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - acc: 0.6483 - loss: 0.8287 
Epoch 8/500
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.6230 - loss: 1.0337
Epoch 9/500
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 911us/step - acc: 0.6410 - loss: 0.7577
Epoch 10/500
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.6495 - loss: 0.8910
Epoch 11/500
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - acc: 0.5991 - loss: 1.3004 
Epoch 12/500
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - acc: 0.6162 - loss: 1.0550 
Epoch 13/500
24/24 ━━━━━━━━━━━━━━━━━━━

In [29]:
pred = (model.predict(x_data) >0.5) + 0
pred

24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 997us/step


array([[1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
    

In [30]:
accuracy_score( y_data, pred)

0.7200520833333334

In [31]:
f1_score( y_data, pred)

np.float64(0.5585215605749486)

In [32]:
confusion_matrix( y_data, pred)

array([[417,  83],
       [132, 136]])

In [37]:
(model.predict( np.array( [[6,148,72,35,0,33.6,0.627,50]])  ) >0.5) +0

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step


array([[1]])

In [35]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]