In [2]:
1/25

0.04

In [2]:
import numpy as np
import cv2

# img = cv2.imread('image/test.png')
img = cv2.imread('cat.jpg')

# 커널을 생성한다.
# kernel = np.ones((5,5),np.float32)/25
kernel = np.ones((5,5),np.float32)/25
# kernel = np.ones((5,5),np.float32)/10


# sharpning kernel
# kernel = np.array([[0, -1,  0],
#                    [-1,  5, -1],
#                     [0, -1,  0]])
print(kernel)

dst = cv2.filter2D(img, -1, kernel)
#convolution 연산을 수행

cv2.imshow('Original', img)
cv2.imshow('Result', dst)

cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

[[0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]]


-1

https://deep-learning-study.tistory.com/142

cv2.filter2D(src, ddepth, kernel, dst=None, anchor=None, delta=None, borderType=None) -> dst

• src : 입력 영상

• ddepth : 출력 영상 데이터 타입. (e.g) cv2.CV_8U, cv2.CV_32F, cv2.CV_64F, -1을 지정하면 src와 같은 타입의 dst 영상을 생성합니다.

• kernel: 필터 마스크 행렬. 실수형.

• anchor: 고정점 위치. (-1, -1)이면 필터 중앙을 고정점으로 사용

• delta: 추가적으로 더할 값

• borderType: 가장자리 픽셀 확장 방식

• dst: 출력 영상

### 평균블러링

In [ ]:
import cv2


img = cv2.imread('image/cat.jpg')
img_blur = cv2.blur(img,(5,5))
# 5 x 5  범위내 이웃 픽셀의 평균을 결과 이미지의 픽셀값으로하는 평균 블러링

cv2.imshow('Original', img)
cv2.imshow('Result', img_blur)

cv2.waitKey(0)
cv2.destroyAllWindows()

cv2.waitKey(1)

### 가우시안블러링

평균값 필터 블러링의 단점은 필터링 대상 위치에서 가까이 있는 픽셀과 멀리 있는 픽셀이 모두 같은 가중치를 사용하여 평균을 계산합니다.

 

 멀리 있는 픽셀의 영향을 많이 받아 필터 결과의 퀄리티가 낮아지게 됩니다.

 

 이러한 단점을 보완하기 위해 가우시안 필터를 많이 사용

<img src="https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2F3hxC7%2FbtqJU4lkGql%2FDctAZcntV6dKoG0JaSgZYK%2Fimg.png">

In [9]:
import cv2


img = cv2.imread('image/cat.jpg')
# img_blur = cv2.GaussianBlur(img,(5,5),0)
img_blur = cv2.GaussianBlur(img,(0,0),2)


cv2.imshow('Original', img)
cv2.imshow('Result', img_blur)

cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

-1

https://deep-learning-study.tistory.com/144

cv2.GaussianBlur(src, ksize, sigmaX, dst=None, sigmaY=None, borderType=None) -> dst

• src: 입력 영상. 각 채널 별로 처리됨.

• dst: 출력 영상. src와 같은 크기, 같은 타입.

• ksize: 가우시안 커널 크기. (0, 0)을 지정하면 sigma 값에 의해 자동 결정됨

• sigmaX: x방향 sigma.

• sigmaY: y방향 sigma. 0이면 sigmaX와 같게 설정.

• borderType: 가장자리 픽셀 확장 방식.

### 중간값 블러링

In [ ]:
cv2.medianBlur(src, ksize, dst=None) -> dst

 src : 입력 영상. 각 채널 별로 처리됨
 ksize : 커널 크기. 1보다 큰 홀수를 지정. 숫자 하나를 집어주면 됌
 dst : 출력 영상, src와 같은 크기, 같은 타입

In [ ]:
https://deep-learning-study.tistory.com/163

In [ ]:
import cv2


img = cv2.imread('image/median.png')
median = cv2.medianBlur(img, 5)

cv2.imshow('Original', img)
cv2.imshow('Result', median)

cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

### 양방향 필터링

In [1]:
import cv2


img = cv2.imread('image/texture.png')
median = cv2.medianBlur(img, 5)
blur = cv2.bilateralFilter(img,9,75,75)

cv2.imshow('Original', img)
cv2.imshow('median', median)
cv2.imshow('blur', blur)

cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

-1

In [ ]:
cv2.bilateralFilter(src, d, sigmaColor, sigmaSpace, dst=None, borderType=None) -> dst

• src: 입력 영상. 8비트 또는 실수형, 1채널 또는 3채널.
• d: 필터링에 사용될 이웃 픽셀의 거리(지름), 음수(-1)를 입력하면 sigmaSpace 값에 의해 자동 결정(권장)
• sigmaColor: 색 공간에서 필터의 표준 편차
• sigmaSpace: 좌표 공간에서 필터의 표준 편차
• dst: 출력 영상. src와 같은 크기, 같은 타입.
• borderType: 가장자리 픽셀 처리 방식