In [1]:
import tensorflow as tf
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [4]:
x_data = np.array( [[0,0],[0,1],[1,0],[1,1]] )
y_data = np.array( [[0],[1],[1],[0]] )

In [5]:
dense = Dense( units=1, input_dim=2, activation='sigmoid')
model = Sequential( [dense])
model.compile( loss='binary_crossentropy', optimizer=Adam(0.1),
              metrics=['acc'] )
h = model.fit( x_data, y_data, epochs=500)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 588ms/step - acc: 0.7500 - loss: 0.7182
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - acc: 0.2500 - loss: 0.7114
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - acc: 0.5000 - loss: 0.7052
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - acc: 0.5000 - loss: 0.7005
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - acc: 0.7500 - loss: 0.6973
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.5000 - loss: 0.6949
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - acc: 0.5000 - loss: 0.6935
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - acc: 0.5000 - loss: 0.6933
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - acc: 0.2500 - loss: 0.6936
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - acc: 0.2500 - loss: 0.6942
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - acc: 0.5000 - loss: 0.6950
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - acc: 0.7500 - loss: 0.6957
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/st

In [6]:
dense1 = Dense( units=100, input_dim=2, activation='sigmoid')# w:2x100, b:100
dense2 = Dense( units=1, input_dim=100, activation='sigmoid')# w:100x1 ,b:1
model = Sequential( [dense1,dense2])
model.compile( loss='binary_crossentropy', optimizer=Adam(0.1),
              metrics=['acc'] )
h = model.fit( x_data, y_data, epochs=500)

Epoch 1/500


c:\Python310\lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 817ms/step - acc: 0.5000 - loss: 0.7024
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - acc: 0.5000 - loss: 2.6804
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - acc: 0.5000 - loss: 1.0396
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - acc: 0.5000 - loss: 1.2662
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - acc: 0.5000 - loss: 1.6843
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.5000 - loss: 1.3487
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - acc: 0.5000 - loss: 0.8152
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - acc: 0.5000 - loss: 0.7427
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - acc: 0.5000 - loss: 1.0209
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.5000 - loss: 1.1247
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - acc: 0.5000 - loss: 1.0093
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - acc: 0.5000 - loss: 0.8073
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - acc: 0.

# dense1(x_data)
z1 = matmul( xdata, w1) + b1
hx1 = sigmoid( z1 )
# dense2(hx1)
z2 = matmul(hx1,w2) + b2
hx = sigmoid(z2)

In [11]:
hx1 = dense1( tf.constant(x_data, tf.float32))
hx = dense2( tf.constant(hx1, tf.float32))
hx

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[2.4925961e-04],
       [9.9939710e-01],
       [9.9937958e-01],
       [2.1522995e-03]], dtype=float32)>

In [10]:
model.predict(x_data)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step


array([[2.4925964e-04],
       [9.9939710e-01],
       [9.9937958e-01],
       [2.1522995e-03]], dtype=float32)

In [9]:
(model.predict(x_data)>0.5) +0

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step


array([[0],
       [1],
       [1],
       [0]])

In [12]:
w, b = dense1.get_weights()

In [14]:
w.shape

(2, 100)

In [16]:
b.shape

(100,)

In [17]:
w, b = dense2.get_weights()

In [19]:
w.shape

(100, 1)

In [21]:
dense1 = Dense( units=64, input_dim=2, activation='relu')# w:2x100, b:100
dense2 = Dense( units=32, input_dim=64, activation='relu')# w:100x1 ,b:1
dense3 = Dense( units=1, input_dim=32, activation='sigmoid')# w:100x1 ,b:1
model = Sequential( [dense1,dense2, dense3])
model.compile( loss='binary_crossentropy', optimizer=Adam(0.1),
              metrics=['acc'] )
h = model.fit( x_data, y_data, epochs=200)

Epoch 1/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 992ms/step - acc: 0.7500 - loss: 0.6931
Epoch 2/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - acc: 0.5000 - loss: 0.6308
Epoch 3/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - acc: 0.5000 - loss: 0.8336
Epoch 4/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.5000 - loss: 0.6300
Epoch 5/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - acc: 0.7500 - loss: 0.4285
Epoch 6/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - acc: 1.0000 - loss: 0.2945
Epoch 7/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - acc: 1.0000 - loss: 0.2299
Epoch 8/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - acc: 1.0000 - loss: 0.1728
Epoch 9/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - acc: 1.0000 - loss: 0.1119
Epoch 10/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - acc: 1.0000 - loss: 0.0672
Epoch 11/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 1.0000 - loss: 0.0383
Epoch 12/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - acc: 1.0000 - loss: 0.0199
Epoch 13/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/st