In [1]:
import tensorflow as tf
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import Sequential, Model
from tensorflow.keras.layers import Dense, Input, Flatten, Conv2D,MaxPool2D
from tensorflow.keras.datasets.fashion_mnist import load_data
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.callbacks import EarlyStopping

In [4]:
x = np.random.randint( 0,256, (10,10,1))
x = x.reshape( 1,10,10,1)
x.shape

(1, 10, 10, 1)

In [6]:
conv = Conv2D( 5, kernel_size=(3,3), input_dim=(10,10,1) )
conv( tf.constant(x,tf.float32) )

c:\Python310\lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


<tf.Tensor: shape=(1, 8, 8, 5), dtype=float32, numpy=
array([[[[-78.41024   ,   5.242166  ,  58.30278   ,  63.309906  ,
           68.61305   ],
         [-32.862797  ,   0.7888661 ,  73.1748    ,  77.502235  ,
          142.2878    ],
         [-70.811386  ,   7.514842  ,  45.32637   ,  -0.9733472 ,
          122.032684  ],
         [-38.85721   ,  -3.2091234 ,  60.432865  , 123.17446   ,
          116.983986  ],
         [-30.112766  ,   1.3971188 ,  79.340324  ,  33.99389   ,
           92.53591   ],
         [-47.399555  , -27.712458  ,  67.55837   , 136.01819   ,
           83.51837   ],
         [-46.652256  , -10.566807  ,  73.492516  , -59.789303  ,
           94.3924    ],
         [-60.06479   ,  59.101788  ,  66.9559    ,  55.025963  ,
          101.81877   ]],

        [[  5.7569995 ,   7.9307003 ,  81.24975   ,  74.858406  ,
          112.98751   ],
         [-79.67386   ,  52.247368  ,  87.40074   ,  19.061825  ,
          110.36843   ],
         [ -6.2428856 , -33.16662 

In [8]:
text_labels = ['t-shirt', 'trouser', 'pullover', 'dress', 'coat',
                   'sandal', 'shirt', 'sneaker', 'bag', 'ankle boot']

In [9]:
(x_train,y_train),(x_test,y_test) = load_data()

In [10]:
x_trainR = x_train.reshape(-1,28,28,1)
x_trainN = x_trainR/255

In [11]:
x_trainN.shape

(60000, 28, 28, 1)

In [12]:
model = Sequential()
model.add( Conv2D(32, kernel_size=(3,3), strides=1, input_shape=(28,28,1),
                  activation='relu', padding='same' ) )
model.add( Conv2D(16, kernel_size=(3,3), activation='relu') )
model.add( MaxPool2D(pool_size=(2,2) ) )
model.add( Flatten() )
model.add( Dense( units=64, activation='relu'))
model.add( Dense( units=10, activation='softmax'))
model.compile( loss='sparse_categorical_crossentropy', 
              optimizer=Adam(0.01) ,metrics=['acc'])
model.fit( x_trainN, y_train, epochs=10)

c:\Python310\lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - acc: 0.8162 - loss: 0.5124
Epoch 2/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - acc: 0.8906 - loss: 0.2925
Epoch 3/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - acc: 0.9009 - loss: 0.2676
Epoch 4/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - acc: 0.9066 - loss: 0.2484
Epoch 5/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - acc: 0.9141 - loss: 0.2324
Epoch 6/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - acc: 0.9160 - loss: 0.2208
Epoch 7/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - acc: 0.9173 - loss: 0.2220
Epoch 8/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - acc: 0.9247 - loss: 0.2020
Epoch 9/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - acc: 0.9230 - loss: 0.2019
Epoch 10/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - acc: 0.9288 - loss: 0.1947


In [18]:
model.layers

[<Conv2D name=conv2d_2, built=True>,
 <Conv2D name=conv2d_3, built=True>,
 <MaxPooling2D name=max_pooling2d, built=True>,
 <Flatten name=flatten, built=True>,
 <Dense name=dense, built=True>,
 <Dense name=dense_1, built=True>]

In [19]:
w,b = model.layers[4].get_weights()

In [20]:
w.shape

(2704, 64)

In [ ]:
x_test[0].reshape( 1,28,28,1)

(28, 28)

In [25]:
model.predict(x_test[0].reshape( 1,28,28,1)/255 ).argmax(axis=1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step


array([9])

In [33]:
conv1 = model.layers[0]( x_test[0].reshape( 1,28,28,1)/255 )
conv2 = model.layers[1]( conv1 )
p = model.layers[2](conv2)
f = model.layers[3](p)
d1 = model.layers[4](f) # 1x1204 1204x64
hx = model.layers[5](d1) # 1x64 64x10
hx

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[3.7576536e-16, 1.0441337e-20, 1.8968686e-17, 7.0631355e-19,
        1.1573853e-16, 1.0543316e-09, 5.0159732e-18, 8.4057421e-05,
        3.6946229e-20, 9.9991596e-01]], dtype=float32)>

In [34]:
model.predict(x_test[0].reshape( 1,28,28,1)/255 )

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step


array([[3.7576536e-16, 1.0441337e-20, 1.8968686e-17, 7.0631355e-19,
        1.1573853e-16, 1.0543316e-09, 5.0159732e-18, 8.4057421e-05,
        3.6946229e-20, 9.9991596e-01]], dtype=float32)

<!-- 1. 1, 28, 28, 32
2. 1, 26, 26, 16
3. (1, 13, 13, 16)
4. (1, 2704) -->