In [1]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, SimpleRNN

In [4]:
x = np.array( [[[1,2],[3,4],[5,6],[7,8]]], dtype=np.float32)
x

array([[[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]]], dtype=float32)

In [5]:
x.shape

(1, 4, 2)

In [6]:
rnn = SimpleRNN( 3, return_sequences= True)
rnn( x )

<tf.Tensor: shape=(1, 4, 3), dtype=float32, numpy=
array([[[-0.4983735 , -0.63773936,  0.97860545],
        [-0.912903  , -0.9240173 ,  0.99972004],
        [-0.99141395, -0.99595755,  0.9999992 ],
        [-0.9983468 , -0.9998355 ,  1.        ]]], dtype=float32)>

In [7]:
w = rnn.get_weights()

In [ ]:
print( w[0].shape)
print( w[1].shape)
print( w[2].shape) # bias

(2, 3)
(3, 3)
(3,)
