In [2]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, SimpleRNN, LSTM, GRU

In [4]:
x = np.array( [[[1,2],[3,4],[5,6],[7,8]]], dtype=np.float32)
x

array([[[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]]], dtype=float32)

In [ ]:
x.shape #(배치사이즈, 타입스텝, 특성데이터갯수)

(1, 4, 2)

In [12]:
rnn = SimpleRNN( 3, return_sequences= True)
rnn( x )

<tf.Tensor: shape=(1, 4, 3), dtype=float32, numpy=
array([[[ 0.4345847 , -0.8421322 ,  0.6314032 ],
        [ 0.68969953, -0.98410875,  0.15828072],
        [ 0.722439  , -0.99984914,  0.14593035],
        [ 0.7181674 , -0.9999964 ,  0.3502284 ]]], dtype=float32)>

In [13]:
w = rnn.get_weights()

In [14]:
print( w[0].shape)
print( w[1].shape)
print( w[2].shape) # bias

(2, 3)
(3, 3)
(3,)


In [15]:
xt1 = np.tanh( np.matmul( [[1,2]], w[0] ) ) + w[2]
xt1

array([[ 0.43458471, -0.8421322 ,  0.63140317]])

In [16]:
xt2 = np.tanh( np.matmul( [[3,4]], w[0] ) + np.matmul(xt1,w[1])) + w[2]
xt2

array([[ 0.68969955, -0.9841088 ,  0.15828074]])

In [17]:
xt3 = np.tanh( np.matmul( [[5,6]], w[0] ) + np.matmul(xt2,w[1])) + w[2]
xt3

array([[ 0.72243894, -0.99984902,  0.14593049]])

In [18]:
xt4 = np.tanh( np.matmul( [[7,8]], w[0] ) + np.matmul(xt3,w[1])) + w[2]
xt4

array([[ 0.71816739, -0.99999637,  0.35022833]])

In [24]:
rnn = SimpleRNN( 3)
rnn( x )

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[-0.3678565 ,  0.99999845, -1.        ]], dtype=float32)>

In [23]:
w = rnn.get_weights()

In [21]:
print( w[0].shape)
print( w[1].shape)
print( w[2].shape) # bias

(2, 10)
(10, 10)
(10,)
