In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from tensorflow.keras.layers import Dense, SimpleRNN, Embedding, LSTM
from tensorflow.keras import Sequential
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.utils import to_categorical
from sklearn import datasets, model_selection
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.preprocessing.text import Tokenizer,text_to_word_sequence
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [2]:
text = '''파이썬 언어는 배우기 쉽다
안녕하세요 반갑습니다
나는 지금 밥을 먹는다'''

In [3]:
t = Tokenizer()
t.fit_on_texts( [text])

In [4]:
t.word_index #단어사전..

{'파이썬': 1,
 '언어는': 2,
 '배우기': 3,
 '쉽다': 4,
 '안녕하세요': 5,
 '반갑습니다': 6,
 '나는': 7,
 '지금': 8,
 '밥을': 9,
 '먹는다': 10}

In [5]:
t.texts_to_sequences( [ '안녕하세요 반갑습니다'] )

[[5, 6]]

In [6]:
s = text.split('\n')
s

['파이썬 언어는 배우기 쉽다', '안녕하세요 반갑습니다', '나는 지금 밥을 먹는다']

In [7]:
sentences = []
for line in s:
    print("line:", line)
    encoded = t.texts_to_sequences([line])[0]
    print("encoded", encoded)
    for i in range(1, len(encoded) ):
        sentence = encoded[:i+1]
        sentences.append( sentence )
print( sentences )

line: 파이썬 언어는 배우기 쉽다
encoded [1, 2, 3, 4]
line: 안녕하세요 반갑습니다
encoded [5, 6]
line: 나는 지금 밥을 먹는다
encoded [7, 8, 9, 10]
[[1, 2], [1, 2, 3], [1, 2, 3, 4], [5, 6], [7, 8], [7, 8, 9], [7, 8, 9, 10]]


In [8]:
sentences

[[1, 2], [1, 2, 3], [1, 2, 3, 4], [5, 6], [7, 8], [7, 8, 9], [7, 8, 9, 10]]

In [9]:
sentences = pad_sequences( sentences )

In [10]:
sentences

array([[ 0,  0,  1,  2],
       [ 0,  1,  2,  3],
       [ 1,  2,  3,  4],
       [ 0,  0,  5,  6],
       [ 0,  0,  7,  8],
       [ 0,  7,  8,  9],
       [ 7,  8,  9, 10]])

In [11]:
x = sentences[:,:-1]
y = sentences[:,-1]

In [16]:
x

array([[0, 0, 1],
       [0, 1, 2],
       [1, 2, 3],
       [0, 0, 5],
       [0, 0, 7],
       [0, 7, 8],
       [7, 8, 9]])

In [12]:
y_data = to_categorical(y)
y_data

array([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [14]:
y_data.shape

(7, 11)

In [44]:
# 10: 단어 집합의 크기(vocabulary size)를 나타냅니다. 여기서는 0부터 9까지 총 10개의 고유한 정수 값이 임베딩될 수 있다.
#2: 임베딩 벡터의 차원 수입니다. 각 단어는 2차원 벡터로 매핑.
# input_length=3: 입력 시퀀스의 길이입니다. 여기서는 3개의 정수로 구성된 시퀀스가 입력으로 들어오게 된다.

# arr = np.array( [[1,2,3,10]]) #에러발생
arr = np.array( [[1,2,3,9]])
# (batch_size, input_length, embedding_dim) 
# 각 정수는 (2,) 크기의 벡터로 변환
e =tf.keras.layers.Embedding(10, 2 ,input_length=3)
# e( arr)
e(x)

c:\Python310\lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


<tf.Tensor: shape=(7, 3, 2), dtype=float32, numpy=
array([[[ 0.04508151, -0.03416552],
        [ 0.04508151, -0.03416552],
        [ 0.02271148, -0.00454824]],

       [[ 0.04508151, -0.03416552],
        [ 0.02271148, -0.00454824],
        [ 0.02976223, -0.02736226]],

       [[ 0.02271148, -0.00454824],
        [ 0.02976223, -0.02736226],
        [ 0.01464588, -0.04270132]],

       [[ 0.04508151, -0.03416552],
        [ 0.04508151, -0.03416552],
        [ 0.0001918 ,  0.03426502]],

       [[ 0.04508151, -0.03416552],
        [ 0.04508151, -0.03416552],
        [ 0.00877631,  0.0440812 ]],

       [[ 0.04508151, -0.03416552],
        [ 0.00877631,  0.0440812 ],
        [-0.02067617,  0.03998235]],

       [[ 0.00877631,  0.0440812 ],
        [-0.02067617,  0.03998235],
        [ 0.01621571,  0.02908143]]], dtype=float32)>

In [23]:
model = Sequential()
model.add( Embedding(10, 2 ,input_length=3) )  #사전의 갯수, 출력갯수(밀집벡터),
model.add( SimpleRNN( 32 ) )
model.add( Dense(11, activation='softmax' ) )
model.compile( loss='categorical_crossentropy', optimizer="adam",
             metrics=['accuracy'] )
model.fit( x, y_data, epochs=200)

Epoch 1/200


c:\Python310\lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - accuracy: 0.1429 - loss: 2.4021
Epoch 2/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.1429 - loss: 2.3973
Epoch 3/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.1429 - loss: 2.3925
Epoch 4/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.1429 - loss: 2.3877
Epoch 5/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.1429 - loss: 2.3827
Epoch 6/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.1429 - loss: 2.3775
Epoch 7/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.1429 - loss: 2.3722
Epoch 8/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.2857 - loss: 2.3667
Epoch 9/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.2857 - loss: 2.3609
Epoch 10/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.2857 - loss: 2.3549
Epoch 11/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.2857 - loss: 2.3486
Epoch 12/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.2857 - loss: 2.3420
Epo

In [20]:
enc = t.texts_to_sequences( ['파이썬 언어는'])
print(enc)
p = pad_sequences( enc,4 )
print(p)
b = model.predict(p).argmax( axis=1)
b

[[1, 2]]
[[0 0 1 2]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step


array([3], dtype=int64)