###  Many-to-Many (다대다 - 순차적 출력)

Sequential API에서도 사용할 수 있습니다. 다만, Sequential API는 단일 출력만 반환하도록 설계되어 있기 때문에, return_state=True를 사용하여 출력과 상태를 동시에 반환하려면 Model 클래스를 사용하는 것이 적합

In [3]:
from numpy import array
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM, SimpleRNN, GRU, Conv2D

In [11]:
train_X = [[[1, 2], [3, 4], [5, 6], [7, 8]]]
train_X = np.array(train_X, dtype=np.float32)
print(train_X.shape)

rnn = SimpleRNN(3,return_state=True)
# rnn = SimpleRNN(3, return_sequences=False, return_state=False)와 동일.
hidden_state ,final_state= rnn(train_X)
print('hidden state : {}, shape: {}'.format(hidden_state, hidden_state.shape))
print('final_state state : {}, shape: {}'.format(final_state, final_state.shape))
w= rnn.get_weights()
print( w[0].shape)
print( w[1].shape)
print( w[2].shape)
print('===========')
xt = np.tanh( np.matmul( [[1,2]], w[0])  ) + w[2]
print( xt)
xt1 = np.tanh(  np.matmul( [[3,4]], w[0]) +  np.matmul( xt, w[1])  ) + w[2]
print( xt1 )

xt2 = np.tanh(  np.matmul( [[5,6]], w[0]) +  np.matmul( xt1, w[1])  ) + w[2]
print( xt2 )

xt3 = np.tanh(  np.matmul( [[7,8]], w[0]) +  np.matmul( xt2, w[1])  ) + w[2]
print( xt3 )


(1, 4, 2)
hidden state : [[-1.          0.9999995   0.86993337]], shape: (1, 3)
final_state state : [[-1.          0.9999995   0.86993337]], shape: (1, 3)
(2, 3)
(3, 3)
(3,)
[[-0.94051176  0.96894974  0.62126022]]
[[-0.99990674  0.99819216  0.87187206]]
[[-0.99999899  0.99996908  0.85425338]]
[[-0.99999998  0.99999953  0.86993332]]


In [4]:
train_X = [[[1, 2], [3, 4], [5, 6], [7, 8]]]
train_X = np.array(train_X, dtype=np.float32)
print(train_X.shape)

rnn = SimpleRNN(3, return_sequences=True)
# rnn = SimpleRNN(3, return_sequences=False, return_state=False)와 동일.
hidden_state = rnn(train_X)
print('hidden state : {}, shape: {}'.format(hidden_state, hidden_state.shape))
w= rnn.get_weights()
print( w[0].shape)
print( w[1].shape)
print( w[2].shape)
print('===========')
xt = np.tanh( np.matmul( [[1,2]], w[0])  ) + w[2]
print( xt)
xt1 = np.tanh(  np.matmul( [[3,4]], w[0]) +  np.matmul( xt, w[1])  ) + w[2]
print( xt1 )

xt2 = np.tanh(  np.matmul( [[5,6]], w[0]) +  np.matmul( xt1, w[1])  ) + w[2]
print( xt2 )

xt3 = np.tanh(  np.matmul( [[7,8]], w[0]) +  np.matmul( xt2, w[1])  ) + w[2]
print( xt3 )


(1, 4, 2)
hidden state : [[[ 0.10620439  0.92773515 -0.73484945]
  [-0.9368867   0.9995614  -0.86854166]
  [-0.99639183  0.9999962  -0.99674207]
  [-0.999507    1.         -0.9995825 ]]], shape: (1, 4, 3)
(2, 3)
(3, 3)
(3,)
[[ 0.10620439  0.92773521 -0.73484934]]
[[-0.93688671  0.99956149 -0.86854158]]
[[-0.99639187  0.9999961  -0.99674207]]
[[-0.9995071   0.99999995 -0.99958248]]


In [7]:
train_X = [[[1, 2], [3, 4], [5, 6], [7, 8]]]
train_X = np.array(train_X, dtype=np.float32)
print(train_X.shape)

# rnn = SimpleRNN(3, return_sequences=True)

rnn = SimpleRNN(3, return_sequences=True, return_state=True)

hidden_state, final_state = rnn(train_X)

print('hidden state : {}, shape: {}'.format(hidden_state, hidden_state.shape))
print( 'final_state',final_state )
w= rnn.get_weights()
print( w[0].shape)
print( w[1].shape)
print( w[2].shape)

print('===========')

xt = np.tanh( np.matmul( [[1,2]], w[0])  ) + w[2]
print( xt)
xt1 = np.tanh(  np.matmul( [[3,4]], w[0]) +  np.matmul( xt, w[1])  ) + w[2]
print( xt1 )

xt2 = np.tanh(  np.matmul( [[5,6]], w[0]) +  np.matmul( xt1, w[1])  ) + w[2]
print( xt2 )

xt3 = np.tanh(  np.matmul( [[7,8]], w[0]) +  np.matmul( xt2, w[1])  ) + w[2]
print( xt3 )


(1, 4, 2)
hidden state : [[[-0.52195054  0.67313045 -0.24293081]
  [-0.9801974  -0.05590766  0.31567287]
  [-0.98768955 -0.29283977  0.64621824]
  [-0.99789995 -0.3144263   0.88130146]]], shape: (1, 4, 3)
final_state tf.Tensor([[-0.99789995 -0.3144263   0.88130146]], shape=(1, 3), dtype=float32)
(2, 3)
(3, 3)
(3,)
[[-0.52195054  0.67313037 -0.24293084]]
[[-0.98019736 -0.05590762  0.3156729 ]]
[[-0.98768951 -0.29283949  0.64621823]]
[[-0.99789997 -0.31442658  0.88130143]]


이 모델은 Many-to-Many 구조를 가지며, 시퀀스의 각 타임스텝에 대한 예측 출력과 함께 최종 은닉 상태(hidden state)도 반환합니다. 이 코드를 좀 더 자세히 설명하면 다음과 같습니다:

데이터 준비:

입력 데이터 X는 (3, 3, 1)의 형태로, 3개의 샘플 각각에 3개의 타임스텝을 가지고, 각 타임스텝마다 1개의 피처(feature)를 갖고 있습니다.
목표값 y도 X와 동일하게 구성되어 있습니다.
모델 구조 정의:

input_layer: 입력 레이어는 (3, 1)의 형태를 가지며, 각 시퀀스는 3개의 타임스텝과 1개의 피처로 구성됩니다.
SimpleRNN 레이어:
유닛의 수는 10이고, return_sequences=True로 설정하여 각 타임스텝의 출력을 반환합니다.
return_state=True는 최종 은닉 상태도 반환하도록 합니다.
Dense 레이어:
RNN 출력을 입력으로 받아 32개 유닛을 갖는 Dense 레이어를 통과한 후, 최종 출력으로 1개 유닛을 가진 Dense 레이어를 거칩니다.
이를 통해 각 타임스텝마다 1차원의 출력을 생성하게 됩니다.
모델 컴파일 및 학습:

손실 함수는 mse (평균 제곱 오차)를 사용하고, adam 옵티마이저로 학습합니다.
model.fit() 함수에서는 y와 더불어 np.zeros((3, 10))를 사용해 초기 상태 값을 지정하여 모델을 학습합니다.
예측 및 출력:

모델의 predict() 함수를 통해 예측을 수행하며, 이때 출력(pred)과 최종 은닉 상태(final_hidden_state)를 함께 반환합니다.
최종 출력은 각 타임스텝마다 1개의 예측 값을 가지는 형태입니다.
이 코드의 요점은 RNN이 시퀀스의 각 타임스텝에 대해 예측을 수행하면서, 마지막 은닉 상태도 함께 반환하여 이후 연속적인 시퀀스 예측에 활용할 수 있도록 합니다.

In [12]:
from tensorflow.keras.layers import SimpleRNN, Dense, Input
from tensorflow.keras.models import Model
import numpy as np

# 입력 데이터 (3개의 샘플, 각 샘플에 3개의 타임스텝, 각 타임스텝에 1개의 피처)
X = np.array([[[0], [1], [2]], [[3], [4], [5]], [[6], [7], [8]]])
y = np.array([[[0], [1], [2]], [[3], [4], [5]], [[6], [7], [8]]])
# 입력 정의
input_layer = Input(shape=(3, 1))

# SimpleRNN 생성, return_sequences=True는 전체 시퀀스 출력, return_state=True는 마지막 상태 반환
rnn_layer, final_state = SimpleRNN(10, return_sequences=True, return_state=True)(input_layer)

# 타임스텝별로 출력을 반환하는 Dense 레이어
dense1 = Dense(32)(rnn_layer)
output_layer = Dense(1)(dense1)


# 모델 생성
model = Model( inputs=input_layer, outputs=[output_layer, final_state])

# 모델 컴파일
model.compile(optimizer='adam', loss='mse')

# 모델 학습
model.fit(X, [y, np.zeros((3, 10))], epochs=100, verbose=0)

# 예측 (출력과 함께 상태 반환)
pred, final_hidden_state = model.predict(X)
print("출력 (Many-to-Many, 순차적 출력):\n", pred)
print("\n최종 상태 (Hidden state):\n", final_hidden_state)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step
출력 (Many-to-Many, 순차적 출력):
 [[[0.25040272]
  [2.3782465 ]
  [3.0833287 ]]

 [[4.405017  ]
  [4.9372067 ]
  [5.36977   ]]

 [[4.9512897 ]
  [5.6381044 ]
  [5.669499  ]]]

최종 상태 (Hidden state):
 [[-0.13062356  0.5998703   0.3546414  -0.75276995 -0.4731373   0.32842627
  -0.6095992   0.27244434  0.29447666 -0.4382644 ]
 [-0.9231241   0.9743647   0.7148374  -0.9901465  -0.8994614   0.8426403
  -0.98266524  0.6335323   0.86066186 -0.98947155]
 [-0.9947557   0.9994367   0.89621377 -0.9997806  -0.9484298   0.98534733
  -0.9986317   0.81775427  0.98279935 -0.99923664]]


# Sequence to Sequence

####  ecoder - decoder

입력 시퀀스:      x1 → x2 → x3 → x4  ...  → xn
                   ↓   ↓   ↓   ↓         ↓
              ┌──→ h1 → h2 → h3 → h4  ...  → hn ─┐   (인코더)
              │                                ↓
              └────────────────────────────────→ z (context vector)
                                               ↓
                                         ┌────→ y1 → y2 → y3 → y4 ... → ym
                                         │        ↓   ↓   ↓   ↓       ↓
                                         └──→ 디코더  (출력 시퀀스 생성)


In [13]:
import numpy as np
from tensorflow.keras.models import Model
from tensorflow.keras.layers import SimpleRNN, Dense, Input

# 입력 시퀀스 (5개의 샘플, 각 샘플에 10개의 타임스텝, 각 타임스텝에 1개의 피처)
encoder_input_data = np.array([[[0], [1], [2], [3], [4], [5], [6], [7], [8], [9]],
                               [[1], [2], [3], [4], [5], [6], [7], [8], [9], [10]],
                               [[2], [3], [4], [5], [6], [7], [8], [9], [10], [11]],
                               [[3], [4], [5], [6], [7], [8], [9], [10], [11], [12]],
                               [[4], [5], [6], [7], [8], [9], [10], [11], [12], [13]]])

# 출력 시퀀스 (목표 값)
decoder_target_data = np.array([[[1], [2], [3], [4], [5], [6], [7], [8], [9], [10]],
                                [[2], [3], [4], [5], [6], [7], [8], [9], [10], [11]],
                                [[3], [4], [5], [6], [7], [8], [9], [10], [11], [12]],
                                [[4], [5], [6], [7], [8], [9], [10], [11], [12], [13]],
                                [[5], [6], [7], [8], [9], [10], [11], [12], [13], [14]]])

# 1. 인코더 (Encoder)
encoder_inputs = Input(shape=(10, 1))  # 10개의 타임스텝, 1개의 피처
encoder_rnn, encoder_state = SimpleRNN(64, return_state=True)(encoder_inputs)

# 2. 디코더 (Decoder)
decoder_inputs = Input(shape=(10, 1))  # 디코더 입력 (타겟 시퀀스)
decoder_rnn = SimpleRNN(64, return_sequences=True)(decoder_inputs, initial_state=encoder_state)

dense1 = Dense(32)(decoder_rnn)
decoder_outputs = Dense(1)(dense1)
# decoder_outputs = Dense(1)(decoder_rnn)

# 인코더-디코더 모델 정의
model = Model([encoder_inputs, decoder_inputs], decoder_outputs)

# 모델 컴파일 및 학습
model.compile(optimizer='adam', loss='mse')
model.fit([encoder_input_data, decoder_target_data], decoder_target_data, epochs=100)

# 모델 요약 출력
model.summary()

# 예측 예시 (입력 시퀀스와 같은 형태로 예측)
pred = model.predict([encoder_input_data, decoder_target_data])
print("\n예측 결과:\n", pred)


Epoch 1/100


c:\Python310\lib\site-packages\keras\src\models\functional.py:225: UserWarning: The structure of `inputs` doesn't match the expected structure: ['keras_tensor_10', 'keras_tensor_13']. Received: the structure of inputs=('*', '*')
  warnings.warn(


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - loss: 60.9444
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 53.8116
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 47.2282
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 41.1905
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 35.6929
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 30.7260
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 26.2741
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 22.3181
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 18.8379
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 15.8130
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 13.2216
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 11.0397
Epoch 13/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 9.2397
Epoch 14/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 7.7897
Epoch 15/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 6.6537
Epoch 16/100
1/1 ━━━━

Model: "functional_2"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer_2       │ (None, 10, 1)     │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ input_layer_3       │ (None, 10, 1)     │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ simple_rnn_10       │ [(None, 64),      │      4,224 │ input_layer_2[0]… │
│ (SimpleRNN)         │ (None, 64)]       │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ simple_rnn_11       │ (None, 10, 64)    │      4,224 │ input_layer_3[0]… │
│ (SimpleRNN)         │                   │            │ simple_rnn_10[0]… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_4 (Dense)     │ (None, 10, 32)    │      2,080 │ simple_rnn_11[0]… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_5 (Dense)     │ (None, 10, 1)     │         33 │ dense_4[0][0]     │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 31,685 (123.77 KB)

 Trainable params: 10,561 (41.25 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 21,124 (82.52 KB)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 159ms/step

예측 결과:
 [[[ 0.866536 ]
  [ 1.7527486]
  [ 2.7305574]
  [ 3.784922 ]
  [ 4.9807878]
  [ 6.161374 ]
  [ 6.9647202]
  [ 7.881544 ]
  [ 8.967268 ]
  [10.067438 ]]

 [[ 2.0850163]
  [ 2.9685295]
  [ 3.9691117]
  [ 5.046056 ]
  [ 6.0709953]
  [ 7.03736  ]
  [ 7.8688498]
  [ 8.894901 ]
  [10.057525 ]
  [11.195173 ]]

 [[ 3.1681793]
  [ 4.0670276]
  [ 5.047119 ]
  [ 6.1419473]
  [ 7.0125275]
  [ 7.9036565]
  [ 8.846662 ]
  [ 9.984621 ]
  [11.1837015]
  [12.142065 ]]

 [[ 4.0948153]
  [ 5.1247263]
  [ 6.077495 ]
  [ 7.1429663]
  [ 7.918845 ]
  [ 8.831289 ]
  [ 9.92354  ]
  [11.120831 ]
  [12.134683 ]
  [12.713817 ]]

 [[ 4.8849444]
  [ 6.1545873]
  [ 7.0989704]
  [ 8.108975 ]
  [ 8.868762 ]
  [ 9.869452 ]
  [11.061658 ]
  [12.092989 ]
  [12.710105 ]
  [13.013659 ]]]


#### encoder_state: **컨텍스트 벡터 (z)**

설명:
- encoder_rnn: 인코더 RNN의 전체 출력(여러 타임스텝에서의 출력). 이 경우에는 마지막 타임스텝의 출력만 필요하므로 return_sequences=False를 기본값으로 사용해 전체 시퀀스를 반환하지 않습니다.
- encoder_state: 인코더의 마지막 타임스텝의 상태를 의미합니다. 이것이 컨텍스트 벡터로, 디코더의 초기 상태로 전달됩니다.

#### 컨텍스트 벡터 (Context Vector)의 역할:
- 인코더는 입력 시퀀스를 처리하며 각 타임스텝에서 상태를 업데이트합니다. 마지막 타임스텝에서 생성된 상태가 입력 시퀀스의 정보가 압축된 고정된 벡터입니다.
- 디코더는 이 벡터를 사용하여 입력 시퀀스에 대한 정보를 바탕으로 출력 시퀀스를 생성합니다.
이 encoder_state는 디코더의 초기 상태로 전달되어, 디코더가 출력 시퀀스를 생성할 때 참조하게 됩니다.

### z (context vector)를 출력하는 코드

In [ ]:
import numpy as np
from tensorflow.keras.models import Model
from tensorflow.keras.layers import SimpleRNN, Dense, Input

# 입력 시퀀스 샘플
encoder_input_data = np.array([[[0], [1], [2], [3], [4], [5], [6], [7], [8], [9]]])

# 1. 인코더 (Encoder)
encoder_inputs = Input(shape=(10, 1))
encoder_rnn, encoder_state = SimpleRNN(64, return_state=True)(encoder_inputs)

# 2. 디코더 (Decoder)
decoder_inputs = Input(shape=(10, 1))
decoder_rnn = SimpleRNN(64, return_sequences=True)(decoder_inputs, initial_state=encoder_state)
decoder_outputs = Dense(1)(decoder_rnn)

# 인코더-디코더 모델 정의
model = Model([encoder_inputs, decoder_inputs], decoder_outputs)

# 모델 컴파일 및 학습
model.compile(optimizer='adam', loss='mse')

# 인코더 모델을 따로 정의하여 context vector 확인
encoder_model = Model(encoder_inputs, encoder_state)

# 예측을 통해 컨텍스트 벡터 확인
context_vector = encoder_model.predict(encoder_input_data)
print("컨텍스트 벡터 (z):\n", context_vector)


#### 설명:
- **encoder_model**은 인코더만을 따로 추출하여, 입력 시퀀스를 처리한 후 **마지막 상태(컨텍스트 벡터)**를 반환하도록 정의한 모델입니다.
- **context_vector**는 인코더에서 생성된 마지막 상태, 즉 **컨텍스트 벡터(z)**입니다.
- 이 값은 디코더의 초기 상태로 전달되어 출력 시퀀스를 생성하는 데 사용됩니다.

#### 결과:
- context_vector는 인코더가 입력 시퀀스를 처리한 후 마지막 타임스텝에서 반환한 64차원의 벡터입니다. 이는 입력 시퀀스의 정보를 압축한 값으로, 디코더에서 출력 시퀀스를 생성할 때 참조합니다.

#### 요약:
- **컨텍스트 벡터 (z)**는 인코더의 마지막 상태를 나타내며, 입력 시퀀스의 전체 정보를 요약한 벡터입니다.
- 디코더는 이 벡터를 기반으로 출력 시퀀스를 생성합니다.
- 위 코드에서 encoder_state가 바로 컨텍스트 벡터이며, 이를 디코더로 전달하여 출력 시퀀스를 생성합니다.

In [5]:
import numpy as np
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Embedding, SimpleRNN, Dense
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# 입력 데이터
input_data = [
    "나는 학교에 간다",
    "나는 밥을 먹는다",
    "그는 운동을 한다",
    "우리는 공부를 한다",
    "그녀는 노래를 부른다"
]

# 출력 데이터 (시작과 종료 토큰 추가)
output_data = [
    "<start> i go to school <end>",
    "<start> i eat food <end>",
    "<start> he exercises <end>",
    "<start> we study <end>",
    "<start> she sings <end>"
]

# 토크나이저 정의 (한글)
input_tokenizer = Tokenizer()
input_tokenizer.fit_on_texts(input_data)
input_sequences = input_tokenizer.texts_to_sequences(input_data)

# 토크나이저 정의 (영어)
output_tokenizer = Tokenizer(filters='')
output_tokenizer.fit_on_texts(output_data)
output_sequences = output_tokenizer.texts_to_sequences(output_data)

# 패딩 처리 (시퀀스 길이를 동일하게 맞춤)
max_input_length = max(len(seq) for seq in input_sequences)
max_output_length = max(len(seq) for seq in output_sequences)

input_sequences_pad = pad_sequences(input_sequences, maxlen=max_input_length, padding='post')
output_sequences_pad = pad_sequences(output_sequences, maxlen=max_output_length, padding='post')

# 임베딩 설정
embedding_dim = 50  # 임베딩 벡터의 차원
num_input_tokens = len(input_tokenizer.word_index) + 1
num_output_tokens = len(output_tokenizer.word_index) + 1

# 인코더 정의
encoder_inputs = Input(shape=(max_input_length,))
encoder_embedding = Embedding(input_dim=num_input_tokens, output_dim=embedding_dim)(encoder_inputs)
encoder_rnn = SimpleRNN(32, return_state=True)
encoder_outputs, state_h = encoder_rnn(encoder_embedding)

# 디코더 정의
decoder_inputs = Input(shape=(max_output_length,))
decoder_embedding_layer = Embedding(input_dim=num_output_tokens, output_dim=embedding_dim)
decoder_embedding = decoder_embedding_layer(decoder_inputs)
decoder_rnn = SimpleRNN(32, return_sequences=True, return_state=True)
decoder_outputs, _ = decoder_rnn(decoder_embedding, initial_state=[state_h])
decoder_dense = Dense(num_output_tokens, activation='softmax')
decoder_outputs = decoder_dense(decoder_outputs)

# Seq2Seq 모델 정의
model = Model([encoder_inputs, decoder_inputs], decoder_outputs)

# 모델 컴파일
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# 출력 데이터를 모델 학습에 맞게 변환 (sparse_categorical_crossentropy를 사용하기 때문에)
output_sequences_pad = np.expand_dims(output_sequences_pad, -1)

# 모델 학습
model.fit([input_sequences_pad, output_sequences_pad], output_sequences_pad, epochs=500, batch_size=16)

# 인코더 모델 정의 (예측을 위해 상태만 반환)
encoder_model = Model(encoder_inputs, state_h)

# 디코더 모델 정의 (예측을 위해 상태를 매 타임스텝에 전달)
decoder_state_input_h = Input(shape=(32,))
decoder_embedding_2 = decoder_embedding_layer(decoder_inputs)
decoder_outputs_2, state_h_2 = decoder_rnn(decoder_embedding_2, initial_state=[decoder_state_input_h])
decoder_outputs_2 = decoder_dense(decoder_outputs_2)
decoder_model = Model(
    [decoder_inputs, decoder_state_input_h],
    [decoder_outputs_2, state_h_2]
)

# 시작 및 종료 토큰 인덱스
start_token = output_tokenizer.word_index['<start>']
end_token = output_tokenizer.word_index['<end>']

# 예측 함수
def predict_sequence(input_text):
    # 입력 시퀀스를 토큰화 및 패딩 처리
    input_sequence = input_tokenizer.texts_to_sequences([input_text])
    input_sequence = pad_sequences(input_sequence, maxlen=max_input_length, padding='post')
    
    # 인코더를 통해 초기 상태를 얻음
    states_value = encoder_model.predict(input_sequence)
    
    # 디코더의 초기 입력은 시작 토큰으로 설정
    target_sequence = np.array([[start_token]])
    predicted_sentence = []
    
    # 디코더 예측 반복
    for _ in range(max_output_length):
        output_tokens, h = decoder_model.predict([target_sequence, states_value])
        sampled_token_index = np.argmax(output_tokens[0, -1, :])
        
        # 종료 토큰이 나오면 중지
        if sampled_token_index == end_token:
            break
        
        # 인덱스에 해당하는 단어를 가져와 예측 문장에 추가
        sampled_word = output_tokenizer.index_word.get(sampled_token_index, '')
        predicted_sentence.append(sampled_word)
        
        # 다음 타임스텝의 입력으로 현재 예측된 단어를 설정
        target_sequence = np.array([[sampled_token_index]])
        states_value = h

    return ' '.join(predicted_sentence)

# 테스트 예제
test_input = "나는 학교에 간다"
predicted_output = predict_sequence(test_input)
print("Input:", test_input)
print("Predicted Output:", predicted_output)


Epoch 1/500


c:\Python310\lib\site-packages\keras\src\models\functional.py:225: UserWarning: The structure of `inputs` doesn't match the expected structure: ['keras_tensor_42', 'keras_tensor_46']. Received: the structure of inputs=('*', '*')
  warnings.warn(


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.1667 - loss: 2.6959
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.2000 - loss: 2.6502
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.3000 - loss: 2.6050
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.4000 - loss: 2.5599
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.5667 - loss: 2.5146
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.6333 - loss: 2.4688
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.6667 - loss: 2.4223
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.7000 - loss: 2.3750
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.7000 - loss: 2.3270
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6667 - loss: 2.2781
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.6667 - loss: 2.2285
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.6667 - loss: 2.1784
Epo

c:\Python310\lib\site-packages\keras\src\models\functional.py:225: UserWarning: The structure of `inputs` doesn't match the expected structure: ['keras_tensor_46', 'keras_tensor_51']. Received: the structure of inputs=('*', '*')
  warnings.warn(


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
Input: 나는 학교에 간다
Predicted Output: <start> i go to school school
