In [33]:
from numpy import array
import numpy as np
import pandas as pd
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM, SimpleRNN, GRU

In [34]:
df = pd.read_csv('data/sample.csv',index_col='date')
df

x
date           
2021-01-01    1
2021-01-02    2
2021-01-03    3
2021-01-04    4
2021-01-05    5
...         ...
2021-04-06   96
2021-04-07   97
2021-04-08   98
2021-04-09   99
2021-04-10  100

[100 rows x 1 columns]

In [35]:
df['x'].values

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100], dtype=int64)

In [36]:
def split_xy1(dataset, time_steps):
    x, y = list(), list()
    for i in range(len(dataset)):
        end_number = i + time_steps
        if end_number > len(dataset) -1:
            break
        tmp_x, tmp_y = dataset[i:end_number], dataset[end_number]
        x.append(tmp_x)
        y.append(tmp_y)
    return np.array(x), np.array(y)

In [37]:
def split_xy2(dataset, time_steps, y_column):
    x, y = list(), list()
    for i in range(len(dataset)):
        x_end_number = i + time_steps
        y_end_number = x_end_number + y_column # 추가
        # if end_number > len(dataset) -1:
        # break
        if y_end_number > len(dataset): # 수정
            break
        tmp_x = dataset[i : x_end_number]
        tmp_y = dataset[x_end_number : y_end_number] # 수정
        x.append(tmp_x)
        y.append(tmp_y)
    return np.array(x), np.array(y)

In [38]:
x, y = split_xy1( df['x'].values, 3 )
print(x)
print('==================')
print(y)

[[ 1  2  3]
 [ 2  3  4]
 [ 3  4  5]
 [ 4  5  6]
 [ 5  6  7]
 [ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]
 [ 9 10 11]
 [10 11 12]
 [11 12 13]
 [12 13 14]
 [13 14 15]
 [14 15 16]
 [15 16 17]
 [16 17 18]
 [17 18 19]
 [18 19 20]
 [19 20 21]
 [20 21 22]
 [21 22 23]
 [22 23 24]
 [23 24 25]
 [24 25 26]
 [25 26 27]
 [26 27 28]
 [27 28 29]
 [28 29 30]
 [29 30 31]
 [30 31 32]
 [31 32 33]
 [32 33 34]
 [33 34 35]
 [34 35 36]
 [35 36 37]
 [36 37 38]
 [37 38 39]
 [38 39 40]
 [39 40 41]
 [40 41 42]
 [41 42 43]
 [42 43 44]
 [43 44 45]
 [44 45 46]
 [45 46 47]
 [46 47 48]
 [47 48 49]
 [48 49 50]
 [49 50 51]
 [50 51 52]
 [51 52 53]
 [52 53 54]
 [53 54 55]
 [54 55 56]
 [55 56 57]
 [56 57 58]
 [57 58 59]
 [58 59 60]
 [59 60 61]
 [60 61 62]
 [61 62 63]
 [62 63 64]
 [63 64 65]
 [64 65 66]
 [65 66 67]
 [66 67 68]
 [67 68 69]
 [68 69 70]
 [69 70 71]
 [70 71 72]
 [71 72 73]
 [72 73 74]
 [73 74 75]
 [74 75 76]
 [75 76 77]
 [76 77 78]
 [77 78 79]
 [78 79 80]
 [79 80 81]
 [80 81 82]
 [81 82 83]
 [82 83 84]
 [83 84 85]
 [84

In [39]:
x, y = split_xy2( df['x'].values, 3 , 2 )
print(x)
print('==================')
print(y)

[[ 1  2  3]
 [ 2  3  4]
 [ 3  4  5]
 [ 4  5  6]
 [ 5  6  7]
 [ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]
 [ 9 10 11]
 [10 11 12]
 [11 12 13]
 [12 13 14]
 [13 14 15]
 [14 15 16]
 [15 16 17]
 [16 17 18]
 [17 18 19]
 [18 19 20]
 [19 20 21]
 [20 21 22]
 [21 22 23]
 [22 23 24]
 [23 24 25]
 [24 25 26]
 [25 26 27]
 [26 27 28]
 [27 28 29]
 [28 29 30]
 [29 30 31]
 [30 31 32]
 [31 32 33]
 [32 33 34]
 [33 34 35]
 [34 35 36]
 [35 36 37]
 [36 37 38]
 [37 38 39]
 [38 39 40]
 [39 40 41]
 [40 41 42]
 [41 42 43]
 [42 43 44]
 [43 44 45]
 [44 45 46]
 [45 46 47]
 [46 47 48]
 [47 48 49]
 [48 49 50]
 [49 50 51]
 [50 51 52]
 [51 52 53]
 [52 53 54]
 [53 54 55]
 [54 55 56]
 [55 56 57]
 [56 57 58]
 [57 58 59]
 [58 59 60]
 [59 60 61]
 [60 61 62]
 [61 62 63]
 [62 63 64]
 [63 64 65]
 [64 65 66]
 [65 66 67]
 [66 67 68]
 [67 68 69]
 [68 69 70]
 [69 70 71]
 [70 71 72]
 [71 72 73]
 [72 73 74]
 [73 74 75]
 [74 75 76]
 [75 76 77]
 [76 77 78]
 [77 78 79]
 [78 79 80]
 [79 80 81]
 [80 81 82]
 [81 82 83]
 [82 83 84]
 [83 84 85]
 [84

In [40]:
df = pd.read_csv('data/international-airline-passengers.txt')
df

time  passengers
0    1949-01         112
1    1949-02         118
2    1949-03         132
3    1949-04         129
4    1949-05         121
..       ...         ...
139  1960-08         606
140  1960-09         508
141  1960-10         461
142  1960-11         390
143  1960-12         432

[144 rows x 2 columns]

In [9]:
# 3개의 타입스탭으로 rnn 으로 학습하여
# 461,360,432 인경우 예측값을 구하시요

In [10]:
# 3개의 타입스탭으로 rnn 으로 학습하여
# 461,360,432 인경우 2개의 예측값을 구하시요

In [41]:
x, y = split_xy1(df['passengers'],3)
print(x)
print('===============')
print(y)

[[112 118 132]
 [118 132 129]
 [132 129 121]
 [129 121 135]
 [121 135 148]
 [135 148 148]
 [148 148 136]
 [148 136 119]
 [136 119 104]
 [119 104 118]
 [104 118 115]
 [118 115 126]
 [115 126 141]
 [126 141 135]
 [141 135 125]
 [135 125 149]
 [125 149 170]
 [149 170 170]
 [170 170 158]
 [170 158 133]
 [158 133 114]
 [133 114 140]
 [114 140 145]
 [140 145 150]
 [145 150 178]
 [150 178 163]
 [178 163 172]
 [163 172 178]
 [172 178 199]
 [178 199 199]
 [199 199 184]
 [199 184 162]
 [184 162 146]
 [162 146 166]
 [146 166 171]
 [166 171 180]
 [171 180 193]
 [180 193 181]
 [193 181 183]
 [181 183 218]
 [183 218 230]
 [218 230 242]
 [230 242 209]
 [242 209 191]
 [209 191 172]
 [191 172 194]
 [172 194 196]
 [194 196 196]
 [196 196 236]
 [196 236 235]
 [236 235 229]
 [235 229 243]
 [229 243 264]
 [243 264 272]
 [264 272 237]
 [272 237 211]
 [237 211 180]
 [211 180 201]
 [180 201 204]
 [201 204 188]
 [204 188 235]
 [188 235 227]
 [235 227 234]
 [227 234 264]
 [234 264 302]
 [264 302 293]
 [302 293 

In [12]:
x.shape
x = x.reshape(-1, 3, 1 )
x

array([[[112],
        [118],
        [132]],

       [[118],
        [132],
        [129]],

       [[132],
        [129],
        [121]],

       [[129],
        [121],
        [135]],

       [[121],
        [135],
        [148]],

       [[135],
        [148],
        [148]],

       [[148],
        [148],
        [136]],

       [[148],
        [136],
        [119]],

       [[136],
        [119],
        [104]],

       [[119],
        [104],
        [118]],

       [[104],
        [118],
        [115]],

       [[118],
        [115],
        [126]],

       [[115],
        [126],
        [141]],

       [[126],
        [141],
        [135]],

       [[141],
        [135],
        [125]],

       [[135],
        [125],
        [149]],

       [[125],
        [149],
        [170]],

       [[149],
        [170],
        [170]],

       [[170],
        [170],
        [158]],

       [[170],
        [158],
        [133]],

       [[158],
        [133],
        [114]],

       [[133]

In [13]:
model = Sequential()
model.add(LSTM(64, activation='relu', input_shape = (3,1)) )
model.add(Dense( units = 32))
model.add(Dense( units = 1))
model.compile(loss = 'mse')
model.fit(x, y, epochs = 1000)

Epoch 1/1000
5/5 [==============================] - 1s 4ms/step - loss: 88446.1641
Epoch 2/1000
5/5 [==============================] - 0s 3ms/step - loss: 71505.9844
Epoch 3/1000
5/5 [==============================] - 0s 3ms/step - loss: 30522.4746
Epoch 4/1000
5/5 [==============================] - 0s 2ms/step - loss: 3458.1628
Epoch 5/1000
5/5 [==============================] - 0s 2ms/step - loss: 2310.9612
Epoch 6/1000
5/5 [==============================] - 0s 2ms/step - loss: 2092.7361
Epoch 7/1000
5/5 [==============================] - 0s 2ms/step - loss: 2034.7997
Epoch 8/1000
5/5 [==============================] - 0s 3ms/step - loss: 1797.0687
Epoch 9/1000
5/5 [==============================] - 0s 2ms/step - loss: 1890.3875
Epoch 10/1000
5/5 [==============================] - 0s 3ms/step - loss: 1910.8291
Epoch 11/1000
5/5 [==============================] - 0s 2ms/step - loss: 1630.0587
Epoch 12/1000
5/5 [==============================] - 0s 2ms/step - loss: 1312.9370
Epoch 13/1

5/5 [==============================] - 0s 2ms/step - loss: 993.8815
Epoch 101/1000
5/5 [==============================] - 0s 2ms/step - loss: 861.4203
Epoch 102/1000
5/5 [==============================] - 0s 2ms/step - loss: 983.0707
Epoch 103/1000
5/5 [==============================] - 0s 2ms/step - loss: 862.6870
Epoch 104/1000
5/5 [==============================] - 0s 2ms/step - loss: 909.4614
Epoch 105/1000
5/5 [==============================] - 0s 2ms/step - loss: 783.9674
Epoch 106/1000
5/5 [==============================] - 0s 2ms/step - loss: 806.3541
Epoch 107/1000
5/5 [==============================] - 0s 2ms/step - loss: 1064.4767
Epoch 108/1000
5/5 [==============================] - 0s 2ms/step - loss: 1028.1326
Epoch 109/1000
5/5 [==============================] - 0s 2ms/step - loss: 956.7567
Epoch 110/1000
5/5 [==============================] - 0s 2ms/step - loss: 798.7647
Epoch 111/1000
5/5 [==============================] - 0s 2ms/step - loss: 742.4377
Epoch 112/1000
5/

5/5 [==============================] - 0s 2ms/step - loss: 826.9276
Epoch 199/1000
5/5 [==============================] - 0s 2ms/step - loss: 865.7516
Epoch 200/1000
5/5 [==============================] - 0s 2ms/step - loss: 990.9473
Epoch 201/1000
5/5 [==============================] - 0s 2ms/step - loss: 912.4718
Epoch 202/1000
5/5 [==============================] - 0s 2ms/step - loss: 985.8500
Epoch 203/1000
5/5 [==============================] - 0s 2ms/step - loss: 755.3849
Epoch 204/1000
5/5 [==============================] - 0s 2ms/step - loss: 845.1290
Epoch 205/1000
5/5 [==============================] - 0s 3ms/step - loss: 1075.3812
Epoch 206/1000
5/5 [==============================] - 0s 2ms/step - loss: 798.1980
Epoch 207/1000
5/5 [==============================] - 0s 2ms/step - loss: 834.9675
Epoch 208/1000
5/5 [==============================] - 0s 2ms/step - loss: 726.0381
Epoch 209/1000
5/5 [==============================] - 0s 2ms/step - loss: 1094.6099
Epoch 210/1000
5/

5/5 [==============================] - 0s 2ms/step - loss: 709.1849
Epoch 297/1000
5/5 [==============================] - 0s 2ms/step - loss: 805.0107
Epoch 298/1000
5/5 [==============================] - 0s 2ms/step - loss: 849.7673
Epoch 299/1000
5/5 [==============================] - 0s 2ms/step - loss: 732.2003
Epoch 300/1000
5/5 [==============================] - 0s 2ms/step - loss: 699.4573
Epoch 301/1000
5/5 [==============================] - 0s 2ms/step - loss: 759.3985
Epoch 302/1000
5/5 [==============================] - 0s 2ms/step - loss: 905.4823
Epoch 303/1000
5/5 [==============================] - 0s 2ms/step - loss: 935.2383
Epoch 304/1000
5/5 [==============================] - 0s 2ms/step - loss: 812.2986
Epoch 305/1000
5/5 [==============================] - 0s 2ms/step - loss: 883.1932
Epoch 306/1000
5/5 [==============================] - 0s 2ms/step - loss: 761.9949
Epoch 307/1000
5/5 [==============================] - 0s 921us/step - loss: 833.2845
Epoch 308/1000
5/

5/5 [==============================] - 0s 2ms/step - loss: 688.5165
Epoch 395/1000
5/5 [==============================] - 0s 2ms/step - loss: 639.5173
Epoch 396/1000
5/5 [==============================] - 0s 2ms/step - loss: 784.2560
Epoch 397/1000
5/5 [==============================] - 0s 2ms/step - loss: 726.5598
Epoch 398/1000
5/5 [==============================] - 0s 2ms/step - loss: 740.9300
Epoch 399/1000
5/5 [==============================] - 0s 2ms/step - loss: 667.2580
Epoch 400/1000
5/5 [==============================] - 0s 2ms/step - loss: 694.9648
Epoch 401/1000
5/5 [==============================] - 0s 2ms/step - loss: 806.7504
Epoch 402/1000
5/5 [==============================] - 0s 344us/step - loss: 862.8687
Epoch 403/1000
5/5 [==============================] - 0s 2ms/step - loss: 769.9513
Epoch 404/1000
5/5 [==============================] - 0s 2ms/step - loss: 803.8765
Epoch 405/1000
5/5 [==============================] - 0s 2ms/step - loss: 705.0876
Epoch 406/1000
5/

5/5 [==============================] - 0s 2ms/step - loss: 787.2922
Epoch 493/1000
5/5 [==============================] - 0s 2ms/step - loss: 613.7293
Epoch 494/1000
5/5 [==============================] - 0s 1ms/step - loss: 883.8245
Epoch 495/1000
5/5 [==============================] - 0s 2ms/step - loss: 698.5339
Epoch 496/1000
5/5 [==============================] - 0s 2ms/step - loss: 742.0239
Epoch 497/1000
5/5 [==============================] - 0s 350us/step - loss: 735.5292
Epoch 498/1000
5/5 [==============================] - 0s 2ms/step - loss: 706.0059
Epoch 499/1000
5/5 [==============================] - 0s 2ms/step - loss: 762.2659
Epoch 500/1000
5/5 [==============================] - 0s 2ms/step - loss: 913.3699
Epoch 501/1000
5/5 [==============================] - 0s 2ms/step - loss: 903.8008
Epoch 502/1000
5/5 [==============================] - 0s 357us/step - loss: 742.3824
Epoch 503/1000
5/5 [==============================] - 0s 2ms/step - loss: 624.3855
Epoch 504/1000


5/5 [==============================] - 0s 2ms/step - loss: 613.2173
Epoch 591/1000
5/5 [==============================] - 0s 2ms/step - loss: 792.0798
Epoch 592/1000
5/5 [==============================] - 0s 2ms/step - loss: 602.8480
Epoch 593/1000
5/5 [==============================] - 0s 2ms/step - loss: 799.2704
Epoch 594/1000
5/5 [==============================] - 0s 2ms/step - loss: 803.8997
Epoch 595/1000
5/5 [==============================] - 0s 2ms/step - loss: 646.2104
Epoch 596/1000
5/5 [==============================] - 0s 2ms/step - loss: 649.3448
Epoch 597/1000
5/5 [==============================] - 0s 2ms/step - loss: 653.3919
Epoch 598/1000
5/5 [==============================] - 0s 2ms/step - loss: 812.7333
Epoch 599/1000
5/5 [==============================] - 0s 2ms/step - loss: 611.1345
Epoch 600/1000
5/5 [==============================] - 0s 2ms/step - loss: 726.4794
Epoch 601/1000
5/5 [==============================] - 0s 2ms/step - loss: 795.4749
Epoch 602/1000
5/5 

5/5 [==============================] - 0s 2ms/step - loss: 767.6107
Epoch 689/1000
5/5 [==============================] - 0s 2ms/step - loss: 678.7349
Epoch 690/1000
5/5 [==============================] - 0s 2ms/step - loss: 718.1584
Epoch 691/1000
5/5 [==============================] - 0s 2ms/step - loss: 677.9561
Epoch 692/1000
5/5 [==============================] - 0s 2ms/step - loss: 656.8093
Epoch 693/1000
5/5 [==============================] - 0s 2ms/step - loss: 564.2092
Epoch 694/1000
5/5 [==============================] - 0s 2ms/step - loss: 962.0620
Epoch 695/1000
5/5 [==============================] - 0s 2ms/step - loss: 797.8137
Epoch 696/1000
5/5 [==============================] - 0s 383us/step - loss: 611.3914
Epoch 697/1000
5/5 [==============================] - 0s 2ms/step - loss: 582.0833
Epoch 698/1000
5/5 [==============================] - 0s 871us/step - loss: 714.5510
Epoch 699/1000
5/5 [==============================] - 0s 2ms/step - loss: 608.4519
Epoch 700/1000


5/5 [==============================] - 0s 2ms/step - loss: 601.4708
Epoch 787/1000
5/5 [==============================] - 0s 2ms/step - loss: 541.6053
Epoch 788/1000
5/5 [==============================] - 0s 2ms/step - loss: 559.9836
Epoch 789/1000
5/5 [==============================] - 0s 2ms/step - loss: 993.4514
Epoch 790/1000
5/5 [==============================] - 0s 812us/step - loss: 567.0797
Epoch 791/1000
5/5 [==============================] - 0s 2ms/step - loss: 515.3914
Epoch 792/1000
5/5 [==============================] - 0s 2ms/step - loss: 771.7120
Epoch 793/1000
5/5 [==============================] - 0s 2ms/step - loss: 675.7067
Epoch 794/1000
5/5 [==============================] - 0s 2ms/step - loss: 724.1358
Epoch 795/1000
5/5 [==============================] - 0s 1ms/step - loss: 838.7208
Epoch 796/1000
5/5 [==============================] - 0s 2ms/step - loss: 702.5465
Epoch 797/1000
5/5 [==============================] - 0s 2ms/step - loss: 798.6046
Epoch 798/1000
5/

5/5 [==============================] - 0s 411us/step - loss: 762.4372
Epoch 885/1000
5/5 [==============================] - 0s 4ms/step - loss: 707.5002
Epoch 886/1000
5/5 [==============================] - 0s 0s/step - loss: 595.6692
Epoch 887/1000
5/5 [==============================] - 0s 0s/step - loss: 696.5701
Epoch 888/1000
5/5 [==============================] - 0s 4ms/step - loss: 631.1860
Epoch 889/1000
5/5 [==============================] - 0s 0s/step - loss: 695.0163
Epoch 890/1000
5/5 [==============================] - 0s 2ms/step - loss: 750.2792
Epoch 891/1000
5/5 [==============================] - 0s 921us/step - loss: 543.4338
Epoch 892/1000
5/5 [==============================] - 0s 1ms/step - loss: 531.1613
Epoch 893/1000
5/5 [==============================] - 0s 2ms/step - loss: 718.2921
Epoch 894/1000
5/5 [==============================] - 0s 2ms/step - loss: 557.4330
Epoch 895/1000
5/5 [==============================] - 0s 2ms/step - loss: 578.2792
Epoch 896/1000
5/5

5/5 [==============================] - 0s 2ms/step - loss: 551.3460
Epoch 983/1000
5/5 [==============================] - 0s 2ms/step - loss: 763.6749
Epoch 984/1000
5/5 [==============================] - 0s 2ms/step - loss: 693.6653
Epoch 985/1000
5/5 [==============================] - 0s 2ms/step - loss: 703.7949
Epoch 986/1000
5/5 [==============================] - 0s 2ms/step - loss: 550.8400
Epoch 987/1000
5/5 [==============================] - 0s 2ms/step - loss: 627.8593
Epoch 988/1000
5/5 [==============================] - 0s 2ms/step - loss: 550.5263
Epoch 989/1000
5/5 [==============================] - 0s 2ms/step - loss: 780.3465
Epoch 990/1000
5/5 [==============================] - 0s 2ms/step - loss: 495.9489
Epoch 991/1000
5/5 [==============================] - 0s 2ms/step - loss: 778.1473
Epoch 992/1000
5/5 [==============================] - 0s 2ms/step - loss: 639.1418
Epoch 993/1000
5/5 [==============================] - 0s 2ms/step - loss: 724.9211
Epoch 994/1000
5/5 

In [14]:
model.predict(array([461,360,432]).reshape(1,3,1))

1/1 [==============================] - 0s 152ms/step


array([[394.86584]], dtype=float32)

In [42]:
x,y=split_xy2(df['passengers'].values, 3 , 2 )

In [43]:
y

array([[129, 121],
       [121, 135],
       [135, 148],
       [148, 148],
       [148, 136],
       [136, 119],
       [119, 104],
       [104, 118],
       [118, 115],
       [115, 126],
       [126, 141],
       [141, 135],
       [135, 125],
       [125, 149],
       [149, 170],
       [170, 170],
       [170, 158],
       [158, 133],
       [133, 114],
       [114, 140],
       [140, 145],
       [145, 150],
       [150, 178],
       [178, 163],
       [163, 172],
       [172, 178],
       [178, 199],
       [199, 199],
       [199, 184],
       [184, 162],
       [162, 146],
       [146, 166],
       [166, 171],
       [171, 180],
       [180, 193],
       [193, 181],
       [181, 183],
       [183, 218],
       [218, 230],
       [230, 242],
       [242, 209],
       [209, 191],
       [191, 172],
       [172, 194],
       [194, 196],
       [196, 196],
       [196, 236],
       [236, 235],
       [235, 229],
       [229, 243],
       [243, 264],
       [264, 272],
       [272,

In [16]:
df['passengers'].values

array([112, 118, 132, 129, 121, 135, 148, 148, 136, 119, 104, 118, 115,
       126, 141, 135, 125, 149, 170, 170, 158, 133, 114, 140, 145, 150,
       178, 163, 172, 178, 199, 199, 184, 162, 146, 166, 171, 180, 193,
       181, 183, 218, 230, 242, 209, 191, 172, 194, 196, 196, 236, 235,
       229, 243, 264, 272, 237, 211, 180, 201, 204, 188, 235, 227, 234,
       264, 302, 293, 259, 229, 203, 229, 242, 233, 267, 269, 270, 315,
       364, 347, 312, 274, 237, 278, 284, 277, 317, 313, 318, 374, 413,
       405, 355, 306, 271, 306, 315, 301, 356, 348, 355, 422, 465, 467,
       404, 347, 305, 336, 340, 318, 362, 348, 363, 435, 491, 505, 404,
       359, 310, 337, 360, 342, 406, 396, 420, 472, 548, 559, 463, 407,
       362, 405, 417, 391, 419, 461, 472, 535, 622, 606, 508, 461, 390,
       432], dtype=int64)

In [17]:
x

array([[112, 118, 132],
       [118, 132, 129],
       [132, 129, 121],
       [129, 121, 135],
       [121, 135, 148],
       [135, 148, 148],
       [148, 148, 136],
       [148, 136, 119],
       [136, 119, 104],
       [119, 104, 118],
       [104, 118, 115],
       [118, 115, 126],
       [115, 126, 141],
       [126, 141, 135],
       [141, 135, 125],
       [135, 125, 149],
       [125, 149, 170],
       [149, 170, 170],
       [170, 170, 158],
       [170, 158, 133],
       [158, 133, 114],
       [133, 114, 140],
       [114, 140, 145],
       [140, 145, 150],
       [145, 150, 178],
       [150, 178, 163],
       [178, 163, 172],
       [163, 172, 178],
       [172, 178, 199],
       [178, 199, 199],
       [199, 199, 184],
       [199, 184, 162],
       [184, 162, 146],
       [162, 146, 166],
       [146, 166, 171],
       [166, 171, 180],
       [171, 180, 193],
       [180, 193, 181],
       [193, 181, 183],
       [181, 183, 218],
       [183, 218, 230],
       [218, 230

In [31]:
y.shape

(141, 1)

In [18]:
y.shape

(140, 2)

In [19]:
x = x.reshape(-1,3,1)

In [20]:
model = Sequential()
model.add( LSTM(32, activation='relu' ,input_shape=(3,1)) )
model.add( Dense( 32))
model.add( Dense( 2))
model.compile(loss='mse', optimizer='adam') 
h=model.fit(x,y,epochs=500)
model.predict(array([461,360,432]).reshape(1,3,1))

Epoch 1/500
5/5 [==============================] - 1s 2ms/step - loss: 98337.6797
Epoch 2/500
5/5 [==============================] - 0s 1ms/step - loss: 91859.8828
Epoch 3/500
5/5 [==============================] - 0s 2ms/step - loss: 86490.4766
Epoch 4/500
5/5 [==============================] - 0s 2ms/step - loss: 80203.5234
Epoch 5/500
5/5 [==============================] - 0s 3ms/step - loss: 72912.2266
Epoch 6/500
5/5 [==============================] - 0s 3ms/step - loss: 60614.3711
Epoch 7/500
5/5 [==============================] - 0s 3ms/step - loss: 44612.8672
Epoch 8/500
5/5 [==============================] - 0s 2ms/step - loss: 24952.3906
Epoch 9/500
5/5 [==============================] - 0s 2ms/step - loss: 9256.9453
Epoch 10/500
5/5 [==============================] - 0s 2ms/step - loss: 4016.8745
Epoch 11/500
5/5 [==============================] - 0s 4ms/step - loss: 3398.8076
Epoch 12/500
5/5 [==============================] - 0s 3ms/step - loss: 3512.1953
Epoch 13/500
5/5 

5/5 [==============================] - 0s 2ms/step - loss: 1423.7802
Epoch 101/500
5/5 [==============================] - 0s 1ms/step - loss: 1559.3086
Epoch 102/500
5/5 [==============================] - 0s 2ms/step - loss: 1412.2352
Epoch 103/500
5/5 [==============================] - 0s 2ms/step - loss: 1418.7091
Epoch 104/500
5/5 [==============================] - 0s 341us/step - loss: 1518.7687
Epoch 105/500
5/5 [==============================] - 0s 2ms/step - loss: 1423.6511
Epoch 106/500
5/5 [==============================] - 0s 2ms/step - loss: 1455.7560
Epoch 107/500
5/5 [==============================] - 0s 1ms/step - loss: 1376.7761
Epoch 108/500
5/5 [==============================] - 0s 394us/step - loss: 1355.5684
Epoch 109/500
5/5 [==============================] - 0s 2ms/step - loss: 1367.4626
Epoch 110/500
5/5 [==============================] - 0s 2ms/step - loss: 1354.8937
Epoch 111/500
5/5 [==============================] - 0s 2ms/step - loss: 1355.7595
Epoch 112/500


5/5 [==============================] - 0s 2ms/step - loss: 1222.7616
Epoch 199/500
5/5 [==============================] - 0s 2ms/step - loss: 1152.3256
Epoch 200/500
5/5 [==============================] - 0s 2ms/step - loss: 1229.3931
Epoch 201/500
5/5 [==============================] - 0s 2ms/step - loss: 1312.8457
Epoch 202/500
5/5 [==============================] - 0s 2ms/step - loss: 1141.9355
Epoch 203/500
5/5 [==============================] - 0s 2ms/step - loss: 1275.1296
Epoch 204/500
5/5 [==============================] - 0s 2ms/step - loss: 1245.9927
Epoch 205/500
5/5 [==============================] - 0s 1ms/step - loss: 1169.5060
Epoch 206/500
5/5 [==============================] - 0s 1ms/step - loss: 1241.5472
Epoch 207/500
5/5 [==============================] - 0s 2ms/step - loss: 1155.8671
Epoch 208/500
5/5 [==============================] - 0s 2ms/step - loss: 1184.0198
Epoch 209/500
5/5 [==============================] - 0s 392us/step - loss: 1245.9578
Epoch 210/500
5/

5/5 [==============================] - 0s 2ms/step - loss: 1243.2057
Epoch 297/500
5/5 [==============================] - 0s 2ms/step - loss: 1285.6467
Epoch 298/500
5/5 [==============================] - 0s 1ms/step - loss: 1268.5481
Epoch 299/500
5/5 [==============================] - 0s 1ms/step - loss: 1162.8085
Epoch 300/500
5/5 [==============================] - 0s 2ms/step - loss: 1303.7511
Epoch 301/500
5/5 [==============================] - 0s 2ms/step - loss: 1175.1226
Epoch 302/500
5/5 [==============================] - 0s 2ms/step - loss: 1150.4124
Epoch 303/500
5/5 [==============================] - 0s 1ms/step - loss: 1265.7135
Epoch 304/500
5/5 [==============================] - 0s 1ms/step - loss: 1132.3215
Epoch 305/500
5/5 [==============================] - 0s 2ms/step - loss: 1194.6359
Epoch 306/500
5/5 [==============================] - 0s 2ms/step - loss: 1166.3213
Epoch 307/500
5/5 [==============================] - 0s 2ms/step - loss: 1110.8019
Epoch 308/500
5/5 

5/5 [==============================] - 0s 2ms/step - loss: 1114.0042
Epoch 395/500
5/5 [==============================] - 0s 2ms/step - loss: 1195.5425
Epoch 396/500
5/5 [==============================] - 0s 2ms/step - loss: 1156.5967
Epoch 397/500
5/5 [==============================] - 0s 2ms/step - loss: 1191.4993
Epoch 398/500
5/5 [==============================] - 0s 1ms/step - loss: 1563.0304
Epoch 399/500
5/5 [==============================] - 0s 2ms/step - loss: 1418.5032
Epoch 400/500
5/5 [==============================] - 0s 2ms/step - loss: 1510.9738
Epoch 401/500
5/5 [==============================] - 0s 2ms/step - loss: 1871.7192
Epoch 402/500
5/5 [==============================] - 0s 2ms/step - loss: 1545.6007
Epoch 403/500
5/5 [==============================] - 0s 2ms/step - loss: 1218.2064
Epoch 404/500
5/5 [==============================] - 0s 409us/step - loss: 1303.2161
Epoch 405/500
5/5 [==============================] - 0s 2ms/step - loss: 1254.9182
Epoch 406/500
5/

5/5 [==============================] - 0s 2ms/step - loss: 1044.1005
Epoch 493/500
5/5 [==============================] - 0s 1ms/step - loss: 1063.5016
Epoch 494/500
5/5 [==============================] - 0s 1ms/step - loss: 1045.1636
Epoch 495/500
5/5 [==============================] - 0s 2ms/step - loss: 1134.0969
Epoch 496/500
5/5 [==============================] - 0s 2ms/step - loss: 1355.9945
Epoch 497/500
5/5 [==============================] - 0s 2ms/step - loss: 1359.3986
Epoch 498/500
5/5 [==============================] - 0s 2ms/step - loss: 1314.6499
Epoch 499/500
5/5 [==============================] - 0s 2ms/step - loss: 1170.8346
Epoch 500/500
1/1 [==============================] - 0s 92ms/step


array([[471.93408, 479.0113 ]], dtype=float32)

In [21]:
from sklearn.preprocessing import MinMaxScaler,StandardScaler

In [22]:
scale = MinMaxScaler()
xN = scale.fit_transform( df['passengers'].values.reshape(-1,1) )

In [23]:
x, y = split_xy1( xN,3 )
print(x)
print('===============')
print(y)

[[[0.01544402]
  [0.02702703]
  [0.05405405]]

 [[0.02702703]
  [0.05405405]
  [0.04826255]]

 [[0.05405405]
  [0.04826255]
  [0.03281853]]

 [[0.04826255]
  [0.03281853]
  [0.05984556]]

 [[0.03281853]
  [0.05984556]
  [0.08494208]]

 [[0.05984556]
  [0.08494208]
  [0.08494208]]

 [[0.08494208]
  [0.08494208]
  [0.06177606]]

 [[0.08494208]
  [0.06177606]
  [0.02895753]]

 [[0.06177606]
  [0.02895753]
  [0.        ]]

 [[0.02895753]
  [0.        ]
  [0.02702703]]

 [[0.        ]
  [0.02702703]
  [0.02123552]]

 [[0.02702703]
  [0.02123552]
  [0.04247104]]

 [[0.02123552]
  [0.04247104]
  [0.07142857]]

 [[0.04247104]
  [0.07142857]
  [0.05984556]]

 [[0.07142857]
  [0.05984556]
  [0.04054054]]

 [[0.05984556]
  [0.04054054]
  [0.08687259]]

 [[0.04054054]
  [0.08687259]
  [0.12741313]]

 [[0.08687259]
  [0.12741313]
  [0.12741313]]

 [[0.12741313]
  [0.12741313]
  [0.1042471 ]]

 [[0.12741313]
  [0.1042471 ]
  [0.05598456]]

 [[0.1042471 ]
  [0.05598456]
  [0.01930502]]

 [[0.05598456

In [24]:
model = Sequential()
model.add(LSTM(64, activation='relu', input_shape = (3,1)) )
model.add(Dense( units = 32))
model.add(Dense( units = 1))
model.compile(loss = 'mse')
model.fit(x, y, epochs = 1000)

Epoch 1/1000
5/5 [==============================] - 1s 2ms/step - loss: 0.1129
Epoch 2/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.0489
Epoch 3/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0267
Epoch 4/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0208
Epoch 5/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0179
Epoch 6/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0152
Epoch 7/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.0131
Epoch 8/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0107
Epoch 9/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0101
Epoch 10/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0089
Epoch 11/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0091
Epoch 12/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0084
Epoch 13/1000
5/5 [==============================

5/5 [==============================] - 0s 2ms/step - loss: 0.0051
Epoch 104/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0051
Epoch 105/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0059
Epoch 106/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0051
Epoch 107/1000
5/5 [==============================] - 0s 3ms/step - loss: 0.0054
Epoch 108/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0054
Epoch 109/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0053
Epoch 110/1000
5/5 [==============================] - 0s 333us/step - loss: 0.0052
Epoch 111/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0050
Epoch 112/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0052
Epoch 113/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0049
Epoch 114/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0049
Epoch 115/1000
5/5 [=====================

5/5 [==============================] - 0s 2ms/step - loss: 0.0037
Epoch 205/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0047
Epoch 206/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0044
Epoch 207/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0040
Epoch 208/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0036
Epoch 209/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0038
Epoch 210/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0043
Epoch 211/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0039
Epoch 212/1000
5/5 [==============================] - 0s 338us/step - loss: 0.0036
Epoch 213/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0045
Epoch 214/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0038
Epoch 215/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0039
Epoch 216/1000
5/5 [=====================

5/5 [==============================] - 0s 2ms/step - loss: 0.0035
Epoch 306/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0037
Epoch 307/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0035
Epoch 308/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.0037
Epoch 309/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0037
Epoch 310/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0034
Epoch 311/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0043
Epoch 312/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0035
Epoch 313/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0040
Epoch 314/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0035
Epoch 315/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0037
Epoch 316/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0036
Epoch 317/1000
5/5 [=======================

5/5 [==============================] - 0s 2ms/step - loss: 0.0042
Epoch 407/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.0036
Epoch 408/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.0034
Epoch 409/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0036
Epoch 410/1000
5/5 [==============================] - 0s 338us/step - loss: 0.0035
Epoch 411/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0039
Epoch 412/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0036
Epoch 413/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0037
Epoch 414/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0035
Epoch 415/1000
5/5 [==============================] - 0s 366us/step - loss: 0.0035
Epoch 416/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0038
Epoch 417/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0038
Epoch 418/1000
5/5 [===================

5/5 [==============================] - 0s 2ms/step - loss: 0.0033
Epoch 508/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0037
Epoch 509/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0033
Epoch 510/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0039
Epoch 511/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0035
Epoch 512/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0033
Epoch 513/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0037
Epoch 514/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0036
Epoch 515/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.0038
Epoch 516/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0034
Epoch 517/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0039
Epoch 518/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0034
Epoch 519/1000
5/5 [=======================

5/5 [==============================] - 0s 2ms/step - loss: 0.0036
Epoch 609/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0036
Epoch 610/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0036
Epoch 611/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.0033
Epoch 612/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0034
Epoch 613/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0036
Epoch 614/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0033
Epoch 615/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0034
Epoch 616/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0038
Epoch 617/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0040
Epoch 618/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0034
Epoch 619/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0035
Epoch 620/1000
5/5 [=======================

5/5 [==============================] - 0s 2ms/step - loss: 0.0037
Epoch 710/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0036
Epoch 711/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0033
Epoch 712/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0037
Epoch 713/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0040
Epoch 714/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0034
Epoch 715/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0036
Epoch 716/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0035
Epoch 717/1000
5/5 [==============================] - 0s 378us/step - loss: 0.0036
Epoch 718/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0034
Epoch 719/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0033
Epoch 720/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0036
Epoch 721/1000
5/5 [=====================

5/5 [==============================] - 0s 1ms/step - loss: 0.0038
Epoch 811/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0035
Epoch 812/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0034
Epoch 813/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0037
Epoch 814/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0036
Epoch 815/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.0033
Epoch 816/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0034
Epoch 817/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0033
Epoch 818/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0034
Epoch 819/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0035
Epoch 820/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0035
Epoch 821/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0036
Epoch 822/1000
5/5 [=======================

5/5 [==============================] - 0s 2ms/step - loss: 0.0032
Epoch 912/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0033
Epoch 913/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0035
Epoch 914/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0035
Epoch 915/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0036
Epoch 916/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0035
Epoch 917/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.0034
Epoch 918/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0038
Epoch 919/1000
5/5 [==============================] - 0s 421us/step - loss: 0.0035
Epoch 920/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.0035
Epoch 921/1000
5/5 [==============================] - 0s 396us/step - loss: 0.0034
Epoch 922/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0034
Epoch 923/1000
5/5 [===================

In [25]:
array([461,360,432]).reshape(-1,1)

array([[461],
       [360],
       [432]])

In [26]:
dt = scale.transform( array([461,360,432]).reshape(-1,1) ).reshape(1,3,1)

In [27]:
p = model.predict(dt)
scale.inverse_transform( p )

1/1 [==============================] - 0s 94ms/step


array([[409.93945]], dtype=float32)

In [28]:
x.shape

(141, 3, 1)