In [29]:
from numpy import array

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM, SimpleRNN, GRU, TimeDistributed

### Many to One

In [2]:
x = array( [[1,2,3], [2,3,4], [3,4,5], [4,5,6]] )
y = array([4,5,6,7])
print('x shape : ', x.shape) # (4,3)
print('y shape : ', y.shape) # (4,)
print(x)

x shape :  (4, 3)
y shape :  (4,)
[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]


In [3]:
x = x.reshape( 4,3,1 ) # ( batch size, sequence length, feature 갯수)
x

array([[[1],
        [2],
        [3]],

       [[2],
        [3],
        [4]],

       [[3],
        [4],
        [5]],

       [[4],
        [5],
        [6]]])

In [28]:
y

array([4, 5, 6, 7])

In [13]:
model = Sequential()
model.add( SimpleRNN(8, activation='relu', input_shape=(3,1) ) )
# model.add( Dense(units=32) )
model.add( Dense(units=1)  )
model.compile( loss='mse', optimizer='adam')
model.fit( x,y, epochs=1000)

Epoch 1/1000
1/1 [==============================] - 0s 402ms/step - loss: 162.5891
Epoch 2/1000
1/1 [==============================] - 0s 996us/step - loss: 160.3420
Epoch 3/1000
1/1 [==============================] - 0s 2ms/step - loss: 158.1177
Epoch 4/1000
1/1 [==============================] - 0s 2ms/step - loss: 155.9165
Epoch 5/1000
1/1 [==============================] - 0s 997us/step - loss: 153.7385
Epoch 6/1000
1/1 [==============================] - 0s 997us/step - loss: 151.5840
Epoch 7/1000
1/1 [==============================] - 0s 2ms/step - loss: 149.4531
Epoch 8/1000
1/1 [==============================] - 0s 2ms/step - loss: 147.3459
Epoch 9/1000
1/1 [==============================] - 0s 997us/step - loss: 145.2625
Epoch 10/1000
1/1 [==============================] - 0s 997us/step - loss: 143.2030
Epoch 11/1000
1/1 [==============================] - 0s 998us/step - loss: 141.1676
Epoch 12/1000
1/1 [==============================] - 0s 2ms/step - loss: 139.1561
Epoch 13/10

1/1 [==============================] - 0s 997us/step - loss: 2.8182
Epoch 200/1000
1/1 [==============================] - 0s 997us/step - loss: 2.7181
Epoch 201/1000
1/1 [==============================] - 0s 997us/step - loss: 2.6209
Epoch 202/1000
1/1 [==============================] - 0s 2ms/step - loss: 2.5264
Epoch 203/1000
1/1 [==============================] - 0s 2ms/step - loss: 2.4347
Epoch 204/1000
1/1 [==============================] - 0s 1ms/step - loss: 2.3457
Epoch 205/1000
1/1 [==============================] - 0s 1ms/step - loss: 2.2593
Epoch 206/1000
1/1 [==============================] - 0s 998us/step - loss: 2.1755
Epoch 207/1000
1/1 [==============================] - 0s 997us/step - loss: 2.0943
Epoch 208/1000
1/1 [==============================] - 0s 2ms/step - loss: 2.0155
Epoch 209/1000
1/1 [==============================] - 0s 2ms/step - loss: 1.9392
Epoch 210/1000
1/1 [==============================] - 0s 2ms/step - loss: 1.8653
Epoch 211/1000
1/1 [=============

1/1 [==============================] - 0s 2ms/step - loss: 0.0282
Epoch 400/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0282
Epoch 401/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0282
Epoch 402/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0282
Epoch 403/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0282
Epoch 404/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0282
Epoch 405/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0281
Epoch 406/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0281
Epoch 407/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0281
Epoch 408/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0281
Epoch 409/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0281
Epoch 410/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0281
Epoch 411/1000
1/1 [=====================

1/1 [==============================] - 0s 2ms/step - loss: 0.0257
Epoch 600/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0256
Epoch 601/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0256
Epoch 602/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0256
Epoch 603/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0256
Epoch 604/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0256
Epoch 605/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0256
Epoch 606/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0256
Epoch 607/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0255
Epoch 608/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0255
Epoch 609/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0255
Epoch 610/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0255
Epoch 611/1000
1/1 [=====

1/1 [==============================] - 0s 723us/step - loss: 0.0228
Epoch 800/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0228
Epoch 801/1000
1/1 [==============================] - 0s 1ms/step - loss: 0.0228
Epoch 802/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0227
Epoch 803/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0227
Epoch 804/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0227
Epoch 805/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0227
Epoch 806/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0227
Epoch 807/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0227
Epoch 808/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0226
Epoch 809/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0226
Epoch 810/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0226
Epoch 811/1000
1/1 [===============

1/1 [==============================] - 0s 997us/step - loss: 0.0198
Epoch 1000/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0197


In [14]:
model.layers

In [15]:
rnnW = model.layers[0].get_weights()
rnnW

[array([[ 0.85238224,  0.78843033,  0.38971534, -0.11858338,  0.3831661 ,
          0.1461121 ,  0.67723125, -0.30398494]], dtype=float32),
 array([[-0.08003663,  0.23052135, -0.01397577, -0.6856493 , -0.10410429,
         -0.46535137, -0.4832448 , -0.10234613],
        [ 0.15317243,  0.08706596,  0.06675948,  0.181767  , -0.30352515,
         -0.5781759 ,  0.32743508,  0.5714365 ],
        [-0.51556015,  0.28807837,  0.32671252,  0.37199208, -0.03142459,
          0.04244997,  0.07375101, -0.4420501 ],
        [-0.6054838 , -0.2762419 , -0.5348994 ,  0.09166655,  0.21824105,
          0.2452178 , -0.14126502,  0.36720976],
        [ 0.31357846,  0.29397568,  0.16688137,  0.07083915,  0.78320605,
         -0.01331047, -0.1921009 ,  0.23145318],
        [-0.06549686, -0.59775734,  0.3789097 , -0.35439885, -0.10668266,
          0.52974224,  0.13869247,  0.10364947],
        [ 0.24015188, -0.20360544, -0.48340777, -0.12364741,  0.23928595,
         -0.25033596,  0.4498624 , -0.48456776],

In [ ]:
## rnn학습 weight 는 3개 

In [16]:
rnnW[0].shape

(1, 8)

In [17]:
rnnW[1].shape

(8, 8)

In [18]:
rnnW[2].shape

(8,)

In [20]:
w, b = model.layers[1].get_weights()

In [21]:
w.shape

(8, 1)

In [22]:
model.predict( array([1,2,3]).reshape( 1,3,1) )

array([[3.778708]], dtype=float32)

### Many to Many

In [24]:
import numpy as np

In [25]:
X = list()
Y = list()
X = [x for x in range(5, 301, 5)]
Y = [y for y in range(20, 316, 5)]

X = np.array(X).reshape(20, 3, 1)
Y = np.array(Y).reshape(20, 3, 1)

In [26]:
X

array([[[  5],
        [ 10],
        [ 15]],

       [[ 20],
        [ 25],
        [ 30]],

       [[ 35],
        [ 40],
        [ 45]],

       [[ 50],
        [ 55],
        [ 60]],

       [[ 65],
        [ 70],
        [ 75]],

       [[ 80],
        [ 85],
        [ 90]],

       [[ 95],
        [100],
        [105]],

       [[110],
        [115],
        [120]],

       [[125],
        [130],
        [135]],

       [[140],
        [145],
        [150]],

       [[155],
        [160],
        [165]],

       [[170],
        [175],
        [180]],

       [[185],
        [190],
        [195]],

       [[200],
        [205],
        [210]],

       [[215],
        [220],
        [225]],

       [[230],
        [235],
        [240]],

       [[245],
        [250],
        [255]],

       [[260],
        [265],
        [270]],

       [[275],
        [280],
        [285]],

       [[290],
        [295],
        [300]]])

In [27]:
Y

array([[[ 20],
        [ 25],
        [ 30]],

       [[ 35],
        [ 40],
        [ 45]],

       [[ 50],
        [ 55],
        [ 60]],

       [[ 65],
        [ 70],
        [ 75]],

       [[ 80],
        [ 85],
        [ 90]],

       [[ 95],
        [100],
        [105]],

       [[110],
        [115],
        [120]],

       [[125],
        [130],
        [135]],

       [[140],
        [145],
        [150]],

       [[155],
        [160],
        [165]],

       [[170],
        [175],
        [180]],

       [[185],
        [190],
        [195]],

       [[200],
        [205],
        [210]],

       [[215],
        [220],
        [225]],

       [[230],
        [235],
        [240]],

       [[245],
        [250],
        [255]],

       [[260],
        [265],
        [270]],

       [[275],
        [280],
        [285]],

       [[290],
        [295],
        [300]],

       [[305],
        [310],
        [315]]])

In [32]:
model = Sequential()
model.add( LSTM( 64, activation='relu', input_shape=(3, 1), return_sequences=True))
model.add( TimeDistributed( Dense(1) ) )
model.compile( loss='mse', optimizer = 'adam' )
model.fit( X, Y, epochs=1000)

Epoch 1/1000
1/1 [==============================] - 1s 583ms/step - loss: 36098.1992
Epoch 2/1000
1/1 [==============================] - 0s 16ms/step - loss: 35849.1328
Epoch 3/1000
1/1 [==============================] - 0s 3ms/step - loss: 35614.5547
Epoch 4/1000
1/1 [==============================] - 0s 3ms/step - loss: 35395.3164
Epoch 5/1000
1/1 [==============================] - 0s 3ms/step - loss: 35179.6172
Epoch 6/1000
1/1 [==============================] - 0s 2ms/step - loss: 34963.1719
Epoch 7/1000
1/1 [==============================] - 0s 2ms/step - loss: 34742.2773
Epoch 8/1000
1/1 [==============================] - 0s 2ms/step - loss: 34513.6602
Epoch 9/1000
1/1 [==============================] - 0s 2ms/step - loss: 34275.7266
Epoch 10/1000
1/1 [==============================] - 0s 2ms/step - loss: 34025.5391
Epoch 11/1000
1/1 [==============================] - 0s 3ms/step - loss: 33759.4883
Epoch 12/1000
1/1 [==============================] - 0s 3ms/step - loss: 33476.414

1/1 [==============================] - 0s 1ms/step - loss: 1304.0216
Epoch 196/1000
1/1 [==============================] - 0s 1ms/step - loss: 1269.8336
Epoch 197/1000
1/1 [==============================] - 0s 2ms/step - loss: 1236.4408
Epoch 198/1000
1/1 [==============================] - 0s 3ms/step - loss: 1204.2970
Epoch 199/1000
1/1 [==============================] - 0s 2ms/step - loss: 1173.5756
Epoch 200/1000
1/1 [==============================] - 0s 2ms/step - loss: 1142.7286
Epoch 201/1000
1/1 [==============================] - 0s 2ms/step - loss: 1112.4916
Epoch 202/1000
1/1 [==============================] - 0s 3ms/step - loss: 1083.2322
Epoch 203/1000
1/1 [==============================] - 0s 2ms/step - loss: 1054.4386
Epoch 204/1000
1/1 [==============================] - 0s 2ms/step - loss: 1026.0197
Epoch 205/1000
1/1 [==============================] - 0s 1ms/step - loss: 998.1701
Epoch 206/1000
1/1 [==============================] - 0s 2ms/step - loss: 970.9156
Epoch 207

1/1 [==============================] - 0s 1ms/step - loss: 33.3672
Epoch 393/1000
1/1 [==============================] - 0s 2ms/step - loss: 33.2864
Epoch 394/1000
1/1 [==============================] - 0s 2ms/step - loss: 33.2787
Epoch 395/1000
1/1 [==============================] - 0s 2ms/step - loss: 33.2620
Epoch 396/1000
1/1 [==============================] - 0s 2ms/step - loss: 33.1850
Epoch 397/1000
1/1 [==============================] - 0s 2ms/step - loss: 33.1092
Epoch 398/1000
1/1 [==============================] - 0s 998us/step - loss: 33.0806
Epoch 399/1000
1/1 [==============================] - 0s 2ms/step - loss: 33.0604
Epoch 400/1000
1/1 [==============================] - 0s 3ms/step - loss: 33.0029
Epoch 401/1000
1/1 [==============================] - 0s 2ms/step - loss: 32.9286
Epoch 402/1000
1/1 [==============================] - 0s 3ms/step - loss: 32.8771
Epoch 403/1000
1/1 [==============================] - 0s 3ms/step - loss: 32.8457
Epoch 404/1000
1/1 [=========

Epoch 492/1000
1/1 [==============================] - 0s 2ms/step - loss: 16.6347
Epoch 493/1000
1/1 [==============================] - 0s 2ms/step - loss: 16.4783
Epoch 494/1000
1/1 [==============================] - 0s 2ms/step - loss: 16.3631
Epoch 495/1000
1/1 [==============================] - 0s 3ms/step - loss: 16.2197
Epoch 496/1000
1/1 [==============================] - 0s 2ms/step - loss: 16.0445
Epoch 497/1000
1/1 [==============================] - 0s 2ms/step - loss: 15.8930
Epoch 498/1000
1/1 [==============================] - 0s 3ms/step - loss: 15.7722
Epoch 499/1000
1/1 [==============================] - 0s 2ms/step - loss: 15.6385
Epoch 500/1000
1/1 [==============================] - 0s 2ms/step - loss: 15.4814
Epoch 501/1000
1/1 [==============================] - 0s 2ms/step - loss: 15.3338
Epoch 502/1000
1/1 [==============================] - 0s 2ms/step - loss: 15.2093
Epoch 503/1000
1/1 [==============================] - 0s 3ms/step - loss: 15.0845
Epoch 504/1000
1

1/1 [==============================] - 0s 2ms/step - loss: 8.2863
Epoch 593/1000
1/1 [==============================] - 0s 2ms/step - loss: 8.2498
Epoch 594/1000
1/1 [==============================] - 0s 2ms/step - loss: 8.2138
Epoch 595/1000
1/1 [==============================] - 0s 2ms/step - loss: 8.1783
Epoch 596/1000
1/1 [==============================] - 0s 2ms/step - loss: 8.1432
Epoch 597/1000
1/1 [==============================] - 0s 3ms/step - loss: 8.1087
Epoch 598/1000
1/1 [==============================] - 0s 2ms/step - loss: 8.0746
Epoch 599/1000
1/1 [==============================] - 0s 2ms/step - loss: 8.0409
Epoch 600/1000
1/1 [==============================] - 0s 2ms/step - loss: 8.0077
Epoch 601/1000
1/1 [==============================] - 0s 2ms/step - loss: 7.9749
Epoch 602/1000
1/1 [==============================] - 0s 3ms/step - loss: 7.9425
Epoch 603/1000
1/1 [==============================] - 0s 2ms/step - loss: 7.9106
Epoch 604/1000
1/1 [=======================

1/1 [==============================] - 0s 2ms/step - loss: 4.6530
Epoch 795/1000
1/1 [==============================] - 0s 2ms/step - loss: 4.6422
Epoch 796/1000
1/1 [==============================] - 0s 2ms/step - loss: 4.6314
Epoch 797/1000
1/1 [==============================] - 0s 2ms/step - loss: 4.6206
Epoch 798/1000
1/1 [==============================] - 0s 2ms/step - loss: 4.6099
Epoch 799/1000
1/1 [==============================] - 0s 2ms/step - loss: 4.5992
Epoch 800/1000
1/1 [==============================] - 0s 2ms/step - loss: 4.5886
Epoch 801/1000
1/1 [==============================] - 0s 2ms/step - loss: 4.5779
Epoch 802/1000
1/1 [==============================] - 0s 2ms/step - loss: 4.5673
Epoch 803/1000
1/1 [==============================] - 0s 2ms/step - loss: 4.5568
Epoch 804/1000
1/1 [==============================] - 0s 2ms/step - loss: 4.5462
Epoch 805/1000
1/1 [==============================] - 0s 1ms/step - loss: 4.5357
Epoch 806/1000
1/1 [=======================

1/1 [==============================] - 0s 2ms/step - loss: 3.7309
Epoch 896/1000
1/1 [==============================] - 0s 2ms/step - loss: 3.7234
Epoch 897/1000
1/1 [==============================] - 0s 2ms/step - loss: 3.7159
Epoch 898/1000
1/1 [==============================] - 0s 2ms/step - loss: 3.7084
Epoch 899/1000
1/1 [==============================] - 0s 2ms/step - loss: 3.7010
Epoch 900/1000
1/1 [==============================] - 0s 2ms/step - loss: 3.6935
Epoch 901/1000
1/1 [==============================] - 0s 998us/step - loss: 3.6861
Epoch 902/1000
1/1 [==============================] - 0s 2ms/step - loss: 3.6787
Epoch 903/1000
1/1 [==============================] - 0s 998us/step - loss: 3.6713
Epoch 904/1000
1/1 [==============================] - 0s 2ms/step - loss: 3.6640
Epoch 905/1000
1/1 [==============================] - 0s 2ms/step - loss: 3.6567
Epoch 906/1000
1/1 [==============================] - 0s 3ms/step - loss: 3.6494
Epoch 907/1000
1/1 [===================

1/1 [==============================] - 0s 997us/step - loss: 3.0497
Epoch 997/1000
1/1 [==============================] - 0s 3ms/step - loss: 3.0435
Epoch 998/1000
1/1 [==============================] - 0s 2ms/step - loss: 3.0373
Epoch 999/1000
1/1 [==============================] - 0s 2ms/step - loss: 3.0311
Epoch 1000/1000
1/1 [==============================] - 0s 3ms/step - loss: 3.0249


In [34]:
arr = np.array( [300,305,310])
model.predict( arr.reshape( 1,3,1) )

array([[[317.89267],
        [320.44742],
        [324.65646]]], dtype=float32)