In [7]:
import tensorflow as tf
import numpy as np

# 테스트
## 테스트
### 테스트
<img src='a.jpg'>

#### 텐서종류

#### scalar

In [2]:
s1 = 10
s2 = 'abc'
s3 = 3.14

#### vector data

In [9]:
v1 = [10,20,30]
v2 = ['aa','bb','cc']
arr = np.array( [11,22,33])
print( type(arr))
arr

<class 'numpy.ndarray'>


array([11, 22, 33])

#### matrix

In [ ]:
m =[ [10,20,30],[40,50,60] ] # 2x3

#### 3d-tensor

In [ ]:
d3 =[ [ [10,20,30],[40,50,60] ],[ [10,20,30],[40,50,60] ] ] #2x2x3

#### 4d-tensor

In [ ]:
d4 =[ [ [ [10,20,30],[40,50,60] ],[ [10,20,30],[40,50,60] ] ],
[ [ [10,20,30],[40,50,60] ],[ [10,20,30],[40,50,60] ] ] ] #2x2x2x3

In [ ]:
#### 텐서노드 만드는 방법
- 1. constant:읽기전용
- 2. Variable: 읽기 쓰기

In [ ]:
## 객체: 속성+메소드
- 객체.속성
- 객체.메소드()

In [5]:
s = 10
c = tf.constant( s )
print( type(c))
c

<class 'tensorflow.python.framework.ops.EagerTensor'>


<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [6]:
c.numpy()

10

In [12]:
my =[10,20,30]
my1 = np.array([10,20,30])
print( type(my))
print( type(my1))

<class 'list'>
<class 'numpy.ndarray'>


In [10]:
v = [10,20,30]
v1 = np.array([10,20,30])
t1 = tf.constant( v ) #tf.constant( v1)
t1

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 20, 30])>

In [11]:
t1.numpy()

array([10, 20, 30])

In [13]:
m =[ [10,20,30],[40,50,60] ]
t2 = tf.constant( m )
t2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10, 20, 30],
       [40, 50, 60]])>

### 그래프 연산이유
- 오차역전파를 쉽게 : backward
- forward 연산

### 연산(산술,관계,논리, ...):
- 1. broad casting:차원이 높은 쪽으로 자동확장
- 2. element wise: 동일한 인덱스끼리 연산

In [14]:
a = tf.constant( 3 )
b = tf.constant( [1,2,3])

In [15]:
# c = tf.multiply( a,b ) #x 연산노드
c = a*b
c

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 6, 9])>

In [17]:
d = tf.add( a,b)
d

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 5, 6])>

In [18]:
e = c+d # tf.add(c,d)
e

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 7, 11, 15])>

In [25]:
# f = tf.constant( [1,2,3])
f = tf.constant( [[1],[2],[3]])
# f = tf.constant( [[1],[2]])
g = tf.constant( [[1,2,3],[4,5,6],[7,8,9]])
h = f+g # tf.add( f,g)

In [26]:
h

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])>

### 행렬곱

In [28]:
i = tf.constant( [[1,2],[3,4]])
j = tf.constant( [[5,6],[7,8]])
k = tf.multiply( i, j)
l = tf.matmul( i,j)

In [32]:
k

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 12],
       [21, 32]])>

In [31]:
l

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 22],
       [43, 50]])>

### 기타 많이 사용 연산자

In [33]:
s = [1,2,3]
# s = tf.constant([1,2,3])
t = tf.square( s ) #s**2
t

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 4, 9])>

In [34]:
u = tf.reduce_mean( s )
u

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [35]:
v = tf.reduce_sum( s )
v

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [36]:
w = tf.reduce_max( s )
w

<tf.Tensor: shape=(), dtype=int32, numpy=3>

### Variable

In [37]:
x = tf.Variable(10)

In [38]:
# x.assign(3) 
# x.assign_add(3)
x.assign_sub(3)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=7>