In [1]:
import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD
import numpy as np
import matplotlib.pyplot as plt

In [2]:
x = np.array( [1,2,3,4,5], np.float32)
y = np.array( [3,5,7,9,11], np.float32)

In [8]:
my=[10,20,30]
print( my )

[10, 20, 30]


In [11]:
class Test:
    def __init__(self, a, b):
        print('생성자함수')
        self.a = a
        self.b = b
    def show( self):
        print( self.a, self.b)
    def __repr__(self):
        return f'a={self.a} b={self.b}'
    def __add__( self, x):
        print('add call')
        return self.a + x
    def __call__( self, x,y):
        print( 'x=',x,'y=',y )
    
obj = Test(10,20)
print(obj) #obj.__repr__()
print( obj+20 ) # obj.__add__(20)
obj(100,200) # obj.__call__(100,200) ## obj[10]  # obj.__setitem__(10)
print( obj.a, obj.b )
obj.show()


생성자함수
a=10 b=20
add call
30
x= 100 y= 200
10 20
10 20


In [15]:
x.reshape( 5,1 )

array([[1.],
       [2.],
       [3.],
       [4.],
       [5.]], dtype=float32)

In [33]:
# 1.forward (__call__):  hx = w*x +b     #   hx = tf.matmul( x,w )+b
# 2.w, b :random 하게 초기화(생성자함수
dense = Dense( units=1, input_dim=1 ) # units(라벨의 갯수), input_dim(특성데이터갯수)
dense( x.reshape( 5,1 ) ) #예측값

<tf.Tensor: shape=(5, 1), dtype=float32, numpy=
array([[1.0221864],
       [2.0443728],
       [3.0665593],
       [4.0887456],
       [5.110932 ]], dtype=float32)>

In [34]:
w, b = dense.get_weights()

In [35]:
w

array([[1.0221864]], dtype=float32)

In [36]:
b

array([0.], dtype=float32)

In [30]:
class MyDense:
    def __init__(self):
        self.w = tf.random.uniform([1])
        self.b = tf.random.uniform([1])
    def __call__(self, x ):
        hx = self.w*x + self.b
        return hx
    def get_weights(self):
        return self.w.numpy(), self.b.numpy()

In [31]:
mydense = MyDense()
mydense(x) # mydense.__call__(x)

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([1.2958114, 1.6448132, 1.993815 , 2.3428168, 2.6918185],
      dtype=float32)>

In [32]:
w,b =mydense.get_weights()
print( w, b)

[0.34900177] [0.94680965]


In [21]:
x

array([1., 2., 3., 4., 5.], dtype=float32)

### 케라스 이용 선형회귀

In [ ]:
dense = Dense( units=1, input_dim=1 )
model = Sequential( [dense])
model.compile( loss='mse', optimizer=SGD(learning_rate=0.01) )
model.fit( x, y, epochs=1000) # w = w-0.01*w미분

In [38]:
w,b =dense.get_weights()
print( w, b)

[[2.0000064]] [0.99997795]


In [40]:
dense( x.reshape(5,1) )  #hx = w*x + b 

<tf.Tensor: shape=(5, 1), dtype=float32, numpy=
array([[ 2.9999843],
       [ 4.999991 ],
       [ 6.999997 ],
       [ 9.000004 ],
       [11.0000105]], dtype=float32)>

In [42]:
model.predict( x ) # 전처리후 forward 연산 dense(x)   # numpy()

1/1 [==============================] - 0s 57ms/step


array([[ 2.9999843],
       [ 4.999991 ],
       [ 6.999997 ],
       [ 9.000004 ],
       [11.0000105]], dtype=float32)

In [44]:
model.predict( [10] ) #dense( 10 ) hx = w*x +b

1/1 [==============================] - 0s 50ms/step


array([[21.000042]], dtype=float32)

In [39]:
x

array([1., 2., 3., 4., 5.], dtype=float32)

In [41]:
y

array([ 3.,  5.,  7.,  9., 11.], dtype=float32)