In [1]:
import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
x_data =np.array( [[1,3],[2,2],[3,1],[4,6],[5,5],[6,4]] ) #공부한시간 ,출석일수
y_data = np.array( [[0],[0],[0],[1],[1],[1]] )

In [4]:
dense = Dense( units=1, input_dim=2, activation='sigmoid')
dense(x_data ) 
# z = matmul( x_data, w) + b
# hx = sigmoid( z )

<tf.Tensor: shape=(6, 1), dtype=float32, numpy=
array([[0.983714  ],
       [0.9565136 ],
       [0.8890095 ],
       [0.99983954],
       [0.99955946],
       [0.9987912 ]], dtype=float32)>

In [5]:
w, b = dense.get_weights()
print( w )
print( b )

[[0.26761997]
 [1.2778031 ]]
[0.]


In [ ]:
dense = Dense( units=1, input_dim=2, activation='sigmoid')
model = Sequential( [dense] )
model.compile( loss='binary_crossentropy', optimizer= Adam(0.1), metrics=['acc'] )
h = model.fit( x_data, y_data, epochs=500)

In [10]:
True+0

1

In [11]:
False + 0 

0

In [12]:
(0.7>0.5) + 0

1

In [20]:
# dense(x_data ) > 0.5 
p = (model.predict( x_data ) > 0.5 ) + 0
p

1/1 [==============================] - 0s 10ms/step


array([[0],
       [0],
       [0],
       [1],
       [1],
       [1]])

In [19]:
model.predict( [[5,6]])

1/1 [==============================] - 0s 35ms/step


array([[0.9981926]], dtype=float32)

In [23]:
(y_data == p).mean()

1.0