In [4]:
import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
Pregnancies: 임신 횟수
Glucose: 포도당 부하 검사 수치
BloodPressure: 혈압(mm Hg)
SkinThickness: 팔 삼두근 뒤쪽의 피하지방 측정값(mm)
Insulin: 혈청 인슐린(mu U/ml)
BMI: 체질량지수(체중(kg)/키(m))^2
DiabetesPedigreeFunction: 당뇨 내력 가중치 값
Age: 나이
Outcome: 클래스 결정 값(0 또는 1)

In [ ]:
15분 퀴즈(케라스)
1. 정규화
2. train, test
3. train의 0번째 행의 예측값
4. train, test 정확도 구하기

In [2]:
df = pd.read_csv('data/pima-indians-diabetes.data.csv')
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [3]:
df.corr()

Pregnancies   Glucose  BloodPressure  SkinThickness  \
Pregnancies                  1.000000  0.129459       0.141282      -0.081672   
Glucose                      0.129459  1.000000       0.152590       0.057328   
BloodPressure                0.141282  0.152590       1.000000       0.207371   
SkinThickness               -0.081672  0.057328       0.207371       1.000000   
Insulin                     -0.073535  0.331357       0.088933       0.436783   
BMI                          0.017683  0.221071       0.281805       0.392573   
DiabetesPedigreeFunction    -0.033523  0.137337       0.041265       0.183928   
Age                          0.544341  0.263514       0.239528      -0.113970   
Outcome                      0.221898  0.466581       0.065068       0.074752   

                           Insulin       BMI  DiabetesPedigreeFunction  \
Pregnancies              -0.073535  0.017683                 -0.033523   
Glucose                   0.331357  0.221071                  0.137337   
BloodPressure             0.088933  0.281805                  0.041265   
SkinThickness             0.436783  0.392573                  0.183928   
Insulin                   1.000000  0.197859                  0.185071   
BMI                       0.197859  1.000000                  0.140647   
DiabetesPedigreeFunction  0.185071  0.140647                  1.000000   
Age                      -0.042163  0.036242                  0.033561   
Outcome                   0.130548  0.292695                  0.173844   

                               Age   Outcome  
Pregnancies               0.544341  0.221898  
Glucose                   0.263514  0.466581  
BloodPressure             0.239528  0.065068  
SkinThickness            -0.113970  0.074752  
Insulin                  -0.042163  0.130548  
BMI                       0.036242  0.292695  
DiabetesPedigreeFunction  0.033561  0.173844  
Age                       1.000000  0.238356  
Outcome                   0.238356  1.000000

In [5]:
x_data = df.iloc[:,:-1].values
y_data = df.iloc[:,[-1]].values

In [6]:
scaleF = MinMaxScaler()
x_dataN = scaleF.fit_transform( x_data )

In [7]:
# stratify: 분류가 train 또는 test 골고루 
x_train, x_test, y_train,y_test = train_test_split( x_dataN, y_data, 
                                                   test_size=0.3, stratify=y_data )

In [8]:
x_train.shape

(537, 8)

In [ ]:
dense = Dense( units=1, input_dim=8, activation='sigmoid')
model = Sequential( [dense] )
model.compile( loss='binary_crossentropy', optimizer= Adam(0.1), metrics=['acc'] )
h = model.fit( x_train, y_train, epochs=500)

In [15]:
(model.predict( x_train[0].reshape( 1,8)) >0.5) +0

1/1 [==============================] - 0s 21ms/step


array([[0]])

In [18]:
#x_data[0]
v= scaleF.transform( [x_data[0]] )
model.predict( v )

1/1 [==============================] - 0s 22ms/step


array([[0.727253]], dtype=float32)

In [23]:
p = (model.predict( x_train ) >0.5 )+0

17/17 [==============================] - 0s 979us/step


In [24]:
accuracy_score( y_train, p )

0.7932960893854749

In [25]:
pt = (model.predict( x_test ) >0.5 )+0

8/8 [==============================] - 0s 0s/step


In [26]:
accuracy_score( y_test, pt )

0.7489177489177489

In [ ]:
## 검정: 정확도, confusion matrix, f1 score

In [27]:
from sklearn.metrics import confusion_matrix, f1_score

In [28]:
p = (model.predict( x_train ) >0.5 )+0

17/17 [==============================] - 0s 891us/step


In [31]:
c = confusion_matrix( y_train, p )
c

array([[312,  38],
       [ 73, 114]], dtype=int64)

In [36]:
import seaborn as sb
import matplotlib
matplotlib.rcParams['font.family'] = 'Malgun Gothic'
matplotlib.rcParams['axes.unicode_minus'] = False

In [ ]:
sb.heatmap( c, annot=True, fmt='d',
           xticklabels=['당뇨아님예측','당뇨예측'],yticklabels=['당뇨아님','당뇨'],
          cmap='Reds')
plt.show()

In [39]:
p = (model.predict( x_train ) >0.5 )+0
f1_score( y_train, p )

17/17 [==============================] - 0s 571us/step


0.672566371681416