In [1]:
import tensorflow as tf
from tensorflow.keras.optimizers import Adam
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
df = pd.read_csv( 'data/softmax.txt', sep=' ', header=None)
df

In [5]:
x_data = df.iloc[:, :2]
y_data = df.iloc[:, 2:]

In [12]:
x = tf.constant( x_data, tf.float32)
y = tf.constant( y_data, tf.float32)

In [6]:
x_data.shape

(8, 2)

In [7]:
y_data.shape

(8, 3)

In [ ]:
initX = tf.initializers.GlorotUniform()
w = tf.Variable( initX(shape=[2,3]) ) #[특성데이터, 라벨]
b = tf.Variable( initX(shape=[3]) ) #[라벨]

In [14]:
def compute_loss():
    z = tf.matmul( x,w ) +b
    cost_i = tf.nn.softmax_cross_entropy_with_logits( labels=y, logits=z )
    c = tf.reduce_mean( cost_i )
    return c

In [ ]:
optimizer = Adam( 0.1 )
for i in range(1000):
    optimizer.minimize( compute_loss, var_list=[w,b] )
    c = compute_loss().numpy()
    print( i, 'cost=', c )

In [20]:
def hxfn( xdata ):
    xd = tf.constant( xdata, tf.float32)
    z = tf.matmul( xd, w ) + b
    hx = tf.nn.softmax( z )
    # return z.numpy(), hx.numpy()
    return hx.numpy()

In [21]:
hxfn( [[5,6]] )

array([[7.9884660e-01, 2.0093505e-01, 2.1833637e-04]], dtype=float32)

In [22]:
hxfn( [[5,6]] ).argmax(axis=1)

array([0], dtype=int64)

In [24]:
hxfn( [[1,2]]).argmax(axis=1)

array([2], dtype=int64)

In [28]:
p = hxfn( x_data ).argmax( axis=1)
p

array([2, 2, 2, 1, 1, 1, 0, 0], dtype=int64)

In [31]:
y_data.values.argmax(axis=1)

array([2, 2, 2, 1, 1, 1, 0, 0], dtype=int64)