In [1]:
import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv( 'data/softmax.txt', sep=' ', header=None)
df

In [3]:
x_data = df.iloc[:, :2].values
y_data = df.iloc[:, 2:].values

In [4]:
# w: 2x3, b:3
# z = matmul( x, w ) + b
# hx = softmax( z )
dense = Dense( units=3, input_dim=2, activation='softmax')
dense(x_data)

<tf.Tensor: shape=(8, 3), dtype=float32, numpy=
array([[0.20825028, 0.4765577 , 0.315192  ],
       [0.17402773, 0.56327635, 0.26269597],
       [0.2423875 , 0.5995795 , 0.15803295],
       [0.13076253, 0.74020153, 0.12903589],
       [0.05527846, 0.8190979 , 0.12562369],
       [0.3818339 , 0.5103536 , 0.10781251],
       [0.10009388, 0.8013962 , 0.09850993],
       [0.07515463, 0.8510765 , 0.07376894]], dtype=float32)>

In [5]:
w, b= dense.get_weights()
print( w )
print('-----------')
print( b )

[[-0.885616   -0.4044757  -0.46851617]
 [-0.30102736 -0.43545985 -0.7207857 ]]
-----------
[0. 0. 0.]


In [ ]:
dense = Dense( units=3, input_dim=2, activation='softmax')
model = Sequential( [dense])
model.compile( loss='categorical_crossentropy', optimizer=Adam(0.1), metrics=['acc'])
model.fit( x_data, y_data, epochs=500)

In [9]:
dense(x_data).numpy().argmax( axis=1)

array([2, 2, 2, 1, 1, 1, 0, 0], dtype=int64)

In [11]:
model.predict( x_data).argmax( axis=1)

1/1 [==============================] - 0s 12ms/step


array([2, 2, 2, 1, 1, 1, 0, 0], dtype=int64)

In [12]:
from sklearn.metrics import accuracy_score

In [13]:
p= model.predict( x_data).argmax( axis=1)

1/1 [==============================] - 0s 18ms/step


In [16]:
r = y_data.argmax( axis=1)

In [17]:
accuracy_score( r, p )

1.0

In [18]:
from sklearn.datasets import load_iris

In [21]:
iris = load_iris(as_frame=True)

In [23]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [26]:
iris['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [ ]:
df = iris['frame']
df

## 케라스 :15분 퀴즈
1. sl:5.1 sw:3.5	pl:1.4 pw: 0.2 종분류예측
2. 정확도

In [29]:
from tensorflow.keras.utils import to_categorical

In [34]:
x_data = df.iloc[:, :-1].values
y_data = to_categorical( df['target'].values )

In [ ]:
df.corr()

In [ ]:
dense = Dense( units=3, input_dim=4, activation='softmax')
model = Sequential( [dense])
model.compile( loss='categorical_crossentropy', optimizer=Adam(0.1), metrics=['acc'])
model.fit( x_data, y_data, epochs=500)

In [42]:
 # sl:5.1 sw:3.5	pl:1.4 pw: 0.2
p =model.predict( [[5.1,3.5,1.4,0.2]]).argmax( axis=1)

1/1 [==============================] - 0s 42ms/step


In [44]:
int(p )

0

In [45]:
iris['target_names'][int(p) ]

'setosa'

In [47]:
x_data.shape

(150, 4)

In [49]:
pred = model.predict( x_data ).argmax(axis=1)

5/5 [==============================] - 0s 1ms/step


In [52]:
r = y_data.argmax(axis=1)

In [53]:
accuracy_score( r, pred)

0.98