In [1]:
import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
x_data = np.array( [[0,0],[0,1],[1,0],[1,1]])
y_data = np.array( [[0],[1],[1],[0]] )

In [ ]:
# z = matmul( x, w ) +b  hx = sigmoid( z )
dense = Dense( units=1, input_dim=2, activation='sigmoid')
dense(x_data)>0.5

In [5]:
w, b= dense.get_weights()
print( w )

[[ 0.07128453]
 [-0.57855386]]


In [ ]:
# w: 2x1, b:1
dense = Dense( units=1, input_dim=2, activation='sigmoid')
model = Sequential( [dense] )
model.compile( loss='binary_crossentropy', optimizer=Adam( 0.1 ), metrics=['acc'])
model.fit( x_data, y_data, epochs= 500 )

In [ ]:
# w1: 2x100, b1:100
dense1 = Dense( units=100, input_dim=2, activation='sigmoid')
# w2: 100x1, b2:1
dense2 = Dense( units=1, input_dim=100, activation='sigmoid')
model = Sequential( [dense1, dense2] )
model.compile( loss='binary_crossentropy', optimizer=Adam( 0.1 ), metrics=['acc'])
model.fit( x_data, y_data, epochs= 500 )

# dense1 학습된 weight
z1 = matmul( x_data, w1 ) + b1
hx1 = sigmoid( z1 )
# dense2 학습된 weight
z = matmul( hx1, w2) + b2
hx = sigmoid( z )
hx

In [11]:
# z1 = matmul( x_data, w1 ) + b1
# hx1 = sigmoid( z1 )
hx1 = dense1( x_data ) # 4x2 2x100 ==> 4x100
# z = matmul( hx1, w2 ) + b2
# hx = sigmoid( z )
hx = dense2( hx1 ) # 4x100 100x1  = 4x1
hx

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[1.9606766e-04],
       [9.9927181e-01],
       [9.9926186e-01],
       [8.2410732e-03]], dtype=float32)>

In [12]:
model.predict( x_data )

1/1 [==============================] - 0s 21ms/step


array([[1.9606766e-04],
       [9.9927181e-01],
       [9.9926186e-01],
       [8.2410732e-03]], dtype=float32)

In [9]:
model.predict( x_data )>0.5

1/1 [==============================] - 0s 17ms/step


array([[False],
       [ True],
       [ True],
       [False]])

In [ ]:
# w1: 2x64, b:64
# w2: 64x32, b:32
# w3: 32x1, b:1
dense1 = Dense( units=64, input_dim=2, activation='sigmoid')
dense2 = Dense( units=32, input_dim=64, activation='sigmoid')
dense3 = Dense( units=1, input_dim=32, activation='sigmoid')
model = Sequential( [dense1, dense2,dense3] )
model.compile( loss='binary_crossentropy', optimizer=Adam( 0.1 ), metrics=['acc'])
model.fit( x_data, y_data, epochs= 500 )