In [1]:
import tensorflow as tf
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, SimpleRNN

In [7]:
x = np.array( [[[1,2],[3,4],[5,6],[7,8]]], np.float32)
print(x.shape)  #(데이터갯수, 타임스텝, 특성갯수)

(1, 4, 2)


In [8]:
rnn = SimpleRNN( 3, return_sequences=True  )

In [9]:
rnn(x)

<tf.Tensor: shape=(1, 4, 3), dtype=float32, numpy=
array([[[ 0.7903166 , -0.422457  , -0.50443906],
        [ 0.64841676, -0.86312   , -0.68279374],
        [ 0.8352502 , -0.92482376, -0.90502423],
        [ 0.9158091 , -0.9708939 , -0.9349646 ]]], dtype=float32)>

In [10]:
w = rnn.get_weights()

In [11]:
len(w)

3

In [14]:
print( w[0].shape )
print( w[1].shape )
print( w[2].shape ) # b

(2, 3)
(3, 3)
(3,)


In [17]:
xt1 = np.tanh( np.matmul( [[1,2]], w[0]) ) + w[2]
xt1

array([[ 0.79031658, -0.42245704, -0.50443907]])

In [19]:
xt2 = np.tanh( np.matmul( [[3,4]], w[0]) + np.matmul( xt1, w[1] ) ) + w[2] 
xt2

array([[ 0.64841671, -0.86311995, -0.68279371]])

In [20]:
xt3 = np.tanh( np.matmul( [[5,6]], w[0]) + np.matmul( xt2, w[1] ) ) + w[2] 
xt3

array([[ 0.83525032, -0.92482382, -0.90502431]])

In [21]:
xt4 = np.tanh( np.matmul( [[7,8]], w[0]) + np.matmul( xt3, w[1] ) ) + w[2] 
xt4

array([[ 0.9158091 , -0.97089397, -0.93496472]])

In [22]:
rnn = SimpleRNN( 3, return_sequences=False  )
rnn( x )

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[-0.9998792 ,  0.99999344,  1.        ]], dtype=float32)>