In [1]:
!pip install opencv-python

   ---------------------------------------- 0.0/38.6 MB ? eta -:--:--
   ---------------------------------------- 0.4/38.6 MB 13.2 MB/s eta 0:00:03
    --------------------------------------- 1.0/38.6 MB 12.1 MB/s eta 0:00:04
   - -------------------------------------- 1.5/38.6 MB 12.0 MB/s eta 0:00:04
   -- ------------------------------------- 2.1/38.6 MB 12.0 MB/s eta 0:00:04
   -- ------------------------------------- 2.6/38.6 MB 12.0 MB/s eta 0:00:04
   --- ------------------------------------ 3.2/38.6 MB 11.9 MB/s eta 0:00:03
   --- ------------------------------------ 3.7/38.6 MB 11.9 MB/s eta 0:00:03
   ---- ----------------------------------- 4.3/38.6 MB 11.9 MB/s eta 0:00:03
   ---- ----------------------------------- 4.8/38.6 MB 11.8 MB/s eta 0:00:03
   ----- ---------------------------------- 5.4/38.6 MB 11.8 MB/s eta 0:00:03
   ------ --------------------------------- 5.9/38.6 MB 11.8 MB/s eta 0:00:03
   ------ --------------------------------- 6.5/38.6 MB 11.8 MB/s eta 0:

In [2]:
import numpy as np
import cv2

In [ ]:
# img = cv2.imread('image/test.png')
img = cv2.imread('cat.jpg')
# 커널을 생성한다.
kernel = np.ones((5,5),np.float32)/25
# kernel = np.ones((5,5),np.float32)/25
# kernel = np.ones((5,5),np.float32)/10

# sharpning kernel
# kernel = np.array([[0, -1,  0],
#                    [-1,  5, -1],
#                     [0, -1,  0]])
print(kernel)

dst = cv2.filter2D(img, -1, kernel)
#convolution 연산을 수행

cv2.imshow('Original', img)
cv2.imshow('Result', dst)

cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

[[0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]]
